### PR TITLE
Fix show ip interfaces

### PR DESCRIPTION
**Pull request by msosyak**
I faced the issue when call `show ip interfaces` on the latest SONiC image(03f82a0107):
```
admin@sonic:~$ show ip interfaces 
sTraceback (most recent call last):
  File "/usr/local/bin/show", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/show/main.py", line 727, in interfaces
    netmask = netaddr.IPAddress(ipaddr['netmask']).netmask_bits()
NameError: global name 'netaddr' is not defined

```
In this [PR](https://github.com/Azure/sonic-utilities/pull/1013)  `netaddr` was removed, but we need it to convert subnet mask to cidr  [here](https://github.com/Azure/sonic-utilities/blob/97ad7cecaf9e64e488790c6efbcc9681b454b954/show/main.py#L728) 
**- What I did**
Fix `NameError: global name 'netaddr' is not defined`
**- How I did it**
import netaddr module
**- How to verify it**
- build SONiC with this changes or manually apply them in the running SONiC image
- run `show ip interfaces`
**- Previous command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ show ip interfaces 
sTraceback (most recent call last):
  File "/usr/local/bin/show", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/show/main.py", line 727, in interfaces
    netmask = netaddr.IPAddress(ipaddr['netmask']).netmask_bits()
NameError: global name 'netaddr' is not defined

```
**- New command output (if the output of a command-line utility has changed)**

```
admin@sonic:~$ show ip interfaces 
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
Ethernet0              10.0.0.1/24          up/up         N/A             N/A
Ethernet4              20.0.0.1/24          up/up         N/A             N/A
Ethernet8              10.0.0.4/31          up/up         ARISTA03T2      10.0.0.5
 * * *
```

### CODE REVIEW

**Comment by msosyak** [comment]
@arlakshm  @jleveque Please review

**Review by prsunny — APPROVED** [review]
Thanks for fixing this.

**Comment by prsunny** [comment]
retest this please

**Comment by jleveque** [comment]
Closing as a duplicate of https://github.com/Azure/sonic-utilities/pull/1126, in which the new import is added in alphabetical order, whereas in this PR it is not.

**Pull request closed without merging**
