### PR TITLE
[201911] Add soft-reboot reboot type

### PR DESCRIPTION
**Pull request by sujinmkang**
#### What I did
Introduce a new reboot named as soft-reboot to perform a kernel reboot instead of platform reboot

#### How I did it
Replace the platform reboot with kernel reboot from cold reboot.

#### How to verify it
Perform soft-reboot on DUT and verify all dockers and ports are up and running as expected as cold reboot
And verify the reboot-cause as soft-reboot

### CODE REVIEW

**Comment by sujinmkang** [comment]
@jleveque and @yxieca can you please review this PR too? This is against on 201911 branch.

**Review by jleveque — APPROVED** [review]
Looks good to me. @yxieca to review, as well.

**Review by yxieca — COMMENTED** [review]
Can you make same review change as requested in #1453?

**Comment by sujinmkang** [comment]
@yxieca  I already made the review changes from the master branch to this branch too. 
https://github.com/Azure/sonic-utilities/pull/1449/commits/c719dcfbf48cb29ba42032b0809e7f23948ed528
Please see the changes on the 2nd commit and let me know if you have any concern. Otherwise, please approve this PR:

**Comment by yxieca** [comment]
@sujinmkang you added watchdog but missed clear_warm_boot renaming.

**Review by yxieca — APPROVED** [review]

**Pull request merged**
