### PR TITLE
show command help text fix.

### PR DESCRIPTION
**Pull request by yutatsuchiyamicrosoft**
#### What I did
Changed the show command help text to be more consistent with eachother. In particular, I made them all have the same format.
#### How I did it
Edited the relevant comments in the show command scripts and the Command-Reference.md documentation.
#### How to verify it
Run show -h.
#### Previous command output (if the output of a command-line utility has changed)
For example, 
lldp                  LLDP (Link Layer Discovery Protocol) information.
#### New command output (if the output of a command-line utility has changed)
For example, 
lldp                  Show LLDP information.

### CODE REVIEW

**Comment by smaheshm** [comment]
Thanks for standardizing the help strings, can you check "./utilities_common/cli.py" too if any updates are required.

**Comment by smaheshm** [comment]
looks good. 'force-push' is not preferred as the PR looses the review comments.

**Review by smaheshm — APPROVED** [review]
Wait for builds to pass before merging.

**Comment by yutatsuchiyamicrosoft** [comment]
> looks good. 'force-push' is not preferred as the PR looses the review comments.

Ah ok, thanks for reviewing- will keep this in mind in the future!

**Comment by JohnSalloway** [comment]
Hi @smaheshm : are you able to merge this change?  Thanks

**Pull request merged**
