### PR TITLE
[201811] Change to use rvtysh when calling the show commands

### PR DESCRIPTION
**Pull request by xumia**
#### What I did
Change to use rvtysh when calling the show commands
Merge code from master and fix code conflict, see #1572

### CODE REVIEW

**Comment by qiluo-msft** [comment]
We don't have `rvtysh` command on 201811 branch

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@xumia Qi is right, there is no rvtysh command in 201811 yet. Can you confirm?

**Comment by yxieca** [comment]
@qiluo-msft rvtysh change is included in 201811 image with this change: https://github.com/Azure/sonic-buildimage/pull/7573

**Review by yxieca — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Comment by xumia** [comment]
For 201811, see https://github.com/Azure/sonic-buildimage/pull/7573

**Pull request merged**
