### PR TITLE
Fix UT failed cause by change pycommon to use swsscommon

### PR DESCRIPTION
**Pull request by liuh-80**
Fix UT failed cause by change sonic_py_common to use swss_common

#### Description
    Fix UT failed cause by change sonic_py_common to use swss_common, here is UT failed message:

          2022-02-28T09:26:11.4706067Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
          2022-02-28T09:26:11.4706457Z scripts/route_check.py:556: in main
          2022-02-28T09:26:11.4706805Z     ret, res= check_routes()
          2022-02-28T09:26:11.4707152Z scripts/route_check.py:491: in check_routes
          2022-02-28T09:26:11.4707567Z     rt_appl_miss = filter_out_local_interfaces(rt_appl_miss)
          2022-02-28T09:26:11.4708035Z scripts/route_check.py:352: in filter_out_local_interfaces
          2022-02-28T09:26:11.4708494Z     chassis_local_intfs = chassis.get_chassis_local_interfaces()
          2022-02-28T09:26:11.4708981Z utilities_common/chassis.py:7: in get_chassis_local_interfaces
          2022-02-28T09:26:11.4709703Z     chassisdb_conf=os.path.join('/usr/share/sonic/device/', platform, "chassisdb.conf")
          2022-02-28T09:26:11.4710280Z /usr/lib/python3.7/posixpath.py:94: in join
          2022-02-28T09:26:11.4710838Z     genericpath._check_arg_types('join', a, *p)
          2022-02-28T09:26:11.4711261Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    The UT failed because device_info.get_platform() return null, to fix this issue, add mock method for device_info.get_platform().

#### Motivation and Context
    pyswss will be deprecate, so sonic_py_common will changed to use swss_common.
    Some UT in this project failed because this change.

#### How Has This Been Tested?
    Pass all UT and sonic-buildimage E2E test.

### CODE REVIEW

**Comment by liuh-80** [comment]
The PR check failed because UT issue in sonic-swss, which already have a PR to fix the issue:
https://github.com/Azure/sonic-swss/pull/2166

**Comment by qiluo-msft** [comment]
Could you add "UT failed" message into PR description?

**Comment by liuh-80** [comment]
> Could you add "UT failed" message into PR description?

PR description updated.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
