### PR TITLE
[201911][fwutil]: Use logger from sonic-py-common

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

Cherry-pick changes of `fwutil/log.py` from https://github.com/Azure/sonic-utilities/pull/1008

**- What I did**
* Reduced code duplication: replaced logger with common implementation

**- How I did it**
* Used logger from `sonic-py-common`

**- How to verify it**
1. `fwutil install chassis component <component_name> fw <fw_path> -y`
2. `fwutil update chassis component <component_name> fw -y`

**- Previous command output (if the output of a command-line utility has changed)**
* N/A

**- New command output (if the output of a command-line utility has changed)**
* N/A

### CODE REVIEW

**Comment by nazariig** [comment]
retest default please

**Comment by nazariig** [comment]
retest please

**Comment by nazariig** [comment]
retest this please

**Review by jleveque — APPROVED** [review]

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Check build is failing for PRs against 201911 branch, because the packaging was changed to a wheel in master, and check build environment was changed accordingly.

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by nazariig** [comment]
Looks like the environment is broken:
```
23:31:32  ============================= test session starts ==============================
23:31:32  platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.7.0, pluggy-0.8.0
23:31:32  rootdir: /sonic/sonic-utilities, inifile: pytest.ini
23:31:32  plugins: cov-2.6.0
23:31:32  collected 38 items / 11 errors
23:31:32  
23:31:32  ==================================== ERRORS ====================================
23:31:32  __________ ERROR collecting sonic-utilities-tests/acl_loader_test.py ___________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/acl_loader_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/acl_loader_test.py:10: in <module>
23:31:32      from acl_loader.main import *
23:31:32  acl_loader/main.py:7: in <module>
23:31:32      import tabulate
23:31:32  E   ImportError: No module named tabulate
23:31:32  ____________ ERROR collecting sonic-utilities-tests/aclshow_test.py ____________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/aclshow_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/aclshow_test.py:12: in <module>
23:31:32      load_source('aclshow', scripts_path+'/aclshow')
23:31:32  scripts/aclshow:29: in <module>
23:31:32      from tabulate import tabulate
23:31:32  E   ImportError: No module named tabulate
23:31:32  __________ ERROR collecting sonic-utilities-tests/counterpoll_test.py __________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/counterpoll_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/counterpoll_test.py:16: in <module>
23:31:32      import counterpoll.main as counterpoll
23:31:32  counterpoll/main.py:5: in <module>
23:31:32      from tabulate import tabulate
23:31:32  E   ImportError: No module named tabulate
23:31:32  __________ ERROR collecting sonic-utilities-tests/drops_group_test.py __________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/drops_group_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/drops_group_test.py:15: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ____________ ERROR collecting sonic-utilities-tests/feature_test.py ____________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/feature_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/feature_test.py:12: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ___________ ERROR collecting sonic-utilities-tests/intfstat_test.py ____________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/intfstat_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/intfstat_test.py:16: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ___________ ERROR collecting sonic-utilities-tests/intfutil_test.py ____________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/intfutil_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/intfutil_test.py:7: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ____________ ERROR collecting sonic-utilities-tests/pfcstat_test.py ____________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/pfcstat_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/pfcstat_test.py:6: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ___________ ERROR collecting sonic-utilities-tests/portstat_test.py ____________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/portstat_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/portstat_test.py:7: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ______________ ERROR collecting sonic-utilities-tests/psu_test.py ______________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/psu_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/psu_test.py:10: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  ______________ ERROR collecting sonic-utilities-tests/sfp_test.py ______________
23:31:32  ImportError while importing test module '/sonic/sonic-utilities/sonic-utilities-tests/sfp_test.py'.
23:31:32  Hint: make sure your test modules/packages have valid Python names.
23:31:32  Traceback:
23:31:32  /usr/lib/python2.7/dist-packages/six.py:709: in exec_
23:31:32      exec("""exec _code_ in _globs_, _locs_""")
23:31:32  sonic-utilities-tests/sfp_test.py:11: in <module>
23:31:32      import show.main as show
23:31:32  show/main.py:6: in <module>
23:31:32      import netifaces
23:31:32  E   ImportError: No module named netifaces
23:31:32  !!!!!!!!!!!!!!!!!!! Interrupted: 11 errors during collection !!!!!!!!!!!!!!!!!!!
23:31:32  =========================== 11 error in 1.18 seconds ===========================
```

**Comment by liat-grozovik** [comment]
retest this please

**Comment by liat-grozovik** [comment]
@jleveque  and @lguohan  can you please approve this merge although the test failure?

**Pull request merged**
