### PR TITLE
[201911][acl] Expand VLAN into VLAN members when creating an ACL table

### PR DESCRIPTION
**Pull request by daall**
Signed-off-by: Danny Allen <daall@microsoft.com>

#### What I did
Ported #1475 to 201911.

#### How I did it
Moved files from tests to sonic-utilities-tests.

#### How to verify it
Run unit tests + run ACL tests against 201911 image with this change and verify there is no regression.

### CODE REVIEW

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Why LGTM did not catch the same issue on master PR?

**Comment by daall** [comment]
> Why LGTM did not catch the same issue on master PR?

Great question! I am not sure but I can put in a fix against master for it as well.

**Comment by daall** [comment]
> > Why LGTM did not catch the same issue on master PR?
> 
> Great question! I am not sure but I can put in a fix against master for it as well.

@qiluo we get an import error if we follow the linter's advice. I am wondering if this is some new thing that is allowed in python3 but not python3? I will do some digging, but we need to leave the import as is for now.

**Comment by qiluo-msft** [comment]
The lgtm is somehow correct. It looks confusing to human, what is the meaning of `config`?
```
import config.main as config
from config.main import expand_vlan_ports, parse_acl_table_info
```

**Comment by daall** [comment]
> The lgtm is somehow correct. It looks confusing to human, what is the meaning of `config`?
> 
> ```
> import config.main as config
> from config.main import expand_vlan_ports, parse_acl_table_info
> ```

It's the "config" cli command. I think I can probably import things in a more structured way to 1) make it less confusing and 2) fix the LGTM warning. Let me play around with it some more.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
