### PR TITLE
[Kdump] Remove the duplicate logic if Kdump was disabled

### PR DESCRIPTION
**Pull request by yozhao101**
Signed-off-by: Yong Zhao <yozhao@microsoft.com>

#### What I did
Recently the following error messages were observed on testbed `str2-7050cx3-acs-01` during nightly testing. Specifically this issue will occur when `hostcfg` daemon is started.

    Apr 5 21:12:15.794016 str2-7050cx3-acs-01 ERR /hostcfgd: sonic-kdump-config --disable - failed: return code - 1, output:#012None
    Apr 5 21:12:15.772139 str2-7050cx3-acs-01 INFO hostcfgd[457569]: Error! Exception[[Errno 2] No such file or directory: '/host/grub/grub.cfg'] occured while processing the command sonic-kdump-config --disable.

The root reason is the path of kernel boot loader configuration file used in `kdump_disable(...)` function was not correct. 

We have two different boot loaders `GRUB` and `Aboot` on different platforms. Paths of kernel boot loader configuration file corresponding to these two boot loaders are different. So `kdump_disable(...)` function should not explicitly use the `grub_cfg` since the function parameter `cmdline_file` already represents the path of kernel boot loader configuration file.

#### How I did it
I removed the duplicate logic in the function `kdump_disable(...)` and use `cmdline_file` to uniquely represent the path of kernel boot loader configuration file.

#### How to verify it
I tested this change on testbed `str2-7050cx3-acs-01`.

#### Previous command output (if the output of a command-line utility has changed)
        admin@str2-7050cx3-acs-02:~$ ls -al /host/machine.conf
        -rw-r--r-- 1 root 88 167 Apr 19 12:47 /host/machine.conf
        admin@str2-7050cx3-acs-02:~$ /usr/local/bin/sonic-kdump-config --disable
        Unable to locate current SONiC image
        admin@str2-7050cx3-acs-02:~$ sudo /usr/local/bin/sonic-kdump-config --disable
        kdump is already disabled
        Error! Exception[[Errno 2] No such file or directory: '/host/grub/grub.cfg'] occured while processing the command sonic-kdump-config --disable.

        admin@str-s6000-on-6:~$ sudo /usr/local/bin/sonic-kdump-config --disable
        kdump is already disabled
        Kdump is already disabled
        admin@str-s6000-on-6:~$ ls -al /host/grub/grub.cfg
        -rw------- 1 root root 2529 Mar 17 21:48 /host/grub/grub.cfg
        admin@str-s6000-on-6:~$

#### New command output (if the output of a command-line utility has changed)
      admin@str2-7050cx3-acs-02:~$ ls -al /host/machine.conf
      -rw-r--r-- 1 root 88 167 Apr 19 12:47 /host/machine.conf
      admin@str2-7050cx3-acs-02:~$ /usr/local/bin/sonic-kdump-config --disable
      Root privileges required for this operation
      admin@str2-7050cx3-acs-02:~$ sudo /usr/local/bin/sonic-kdump-config --disable
      kdump is already disabled

      admin@str-s6000-on-6:~$ ls -al /host/grub/grub.cfg
      -rw------- 1 root root 2529 Mar 17 21:48 /host/grub/grub.cfg
      admin@str-s6000-on-6:~$ sudo /usr/local/bin/sonic-kdump-config --disable
      kdump is already disabled
      admin@str-s6000-on-6:~$

### CODE REVIEW

**Comment by yxieca** [comment]
If this is boot loader specific change, can you also test on a grub system and a uboot system?

**Comment by qiluo-msft** [comment]
> def cmd_kdump_disable(verbose, image=get_current_image()):

Add unit test into this repo?

---
Refers to: scripts/sonic-kdump-config:511 in 7e58651. [](commit_id = 7e586513a0778f02aec60556649ef14ae898c895, deletion_comment = False)

**Comment by yozhao101** [comment]
I will add unit test and manually testing results as well.

**Comment by yozhao101** [comment]
> > def cmd_kdump_disable(verbose, image=get_current_image()):
> 
> Add unit test into this repo?
> 
> Refers to: scripts/sonic-kdump-config:511 in [7e58651](https://github.com/Azure/sonic-utilities/commit/7e586513a0778f02aec60556649ef14ae898c895). [](commit_id = [7e58651](https://github.com/Azure/sonic-utilities/commit/7e586513a0778f02aec60556649ef14ae898c895), deletion_comment = False)

@qiluo-msft Can you please help me review this PR again?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
