### PR TITLE
[CLI][pfcwd][start] Fix port validation issue when specifying port options in Multi ASIC platform

### PR DESCRIPTION
**Pull request by smaheshm**
**- What I did**

When ports are specified as option to 'pfcwd start', port validation fails on multi ASIC platform as the validation logic is executed on each ASIC namespace. Validation for valid ports fails as the port exits in only one namespace and not in others.

Fixed port validation logic for multi ASIC platform.

**- How I did it**

Changed logic to perform port validation after collecting ports from all namespaces. If port validation fails there is no config change on other valid ports.

**- How to verify it**

Manual verification. (pytest does not support config change tests yet). Verified pytests for regression.

```
Before on Multi-ASIC (Ethernet0 is a valid port on ASIC0):

admin@str-nswitch-acs-2:~$ sudo pfcwd start --action drop --restoration-time 200 Ethernet0 200
Usage: pfcwd start [OPTIONS] [PORTS]... DETECTION_TIME

Error: Bad command line format. Try 'pfcwd start --help' for usage
admin@str-nswitch-acs-2:~$

After:

admin@str2-nswitch-acs-4:~$ sudo pfcwd start --action drop --restoration-time 200 Ethernet0 200
admin@str2-nswitch-acs-4:~$ sudo pfcwd start --action drop --restoration-time 200 Ethernet0 Ethernet128 200
admin@str2-nswitch-acs-4:~$ sudo pfcwd start --action drop --restoration-time 200 Ethernet0 Ethernet128 Ethernet500 200
Failed to run command, invalid options:
Ethernet500
admin@str2-nswitch-acs-4:~$ sudo pfcwd start --action drop --restoration-time 200 all 200
admin@str2-nswitch-acs-4:~$ sudo pfcwd start --action drop --restoration-time 200 all Ethernet500 200
Failed to run command, invalid options:
Ethernet500
admin@str2-nswitch-acs-4:~$

```

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
🔔

**Review by neethajohn — APPROVED** [review]

**Comment by lguohan** [comment]
> Manual verification. (pytest does not support config change tests yet). Verified pytests for regression.
this is not acceptable. Please fix the infrastructure first. New pr without such pytest support will be reverted. Please talk to leads to fix it.

**Comment by smaheshm** [comment]
> > Manual verification. (pytest does not support config change tests yet). Verified pytests for regression.
> 
> this is not acceptable. Please fix the infrastructure first. New pr without such pytest support will be reverted. Please talk to leads to fix it.

This is planned for this month.

**Comment by abdosi** [comment]
@smaheshm Please check the 201911 commit if the cheery-pick is fine.

**Comment by smaheshm** [comment]
> @smaheshm Please check the 201911 commit if the cheery-pick is fine.



> @smaheshm Please check the 201911 commit if the cheery-pick is fine.

Looks good.

**Pull request merged**
