### PR TITLE
[debug dump util] Changes for EVPN and VxLAN dump module

### PR DESCRIPTION
**Pull request by dgsudharsan**
Signed-off-by: Sudharsan Dhamal Gopalarathnam <sudharsand@nvidia.com>

#### What I did
Added dump utility for EVPN and VxLAN related modules

#### How I did it
Added changes implementing dump for vxlan and evpn tables

#### How to verify it
Added UT to verify the changes.

#### New command output (if the output of a command-line utility has changed)

```
dump state vxlan_tunnel vtep_1336
{
    "vtep_1336": {
        "CONFIG_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL|vtep_1336": {
                        "src_ip": "10.1.0.32"
                    }
                }
            ],
            "tables_not_found": []
        },
        "APPL_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL_TABLE:vtep_1336": {
                        "src_ip": "10.1.0.32"
                    }
                }
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL:oid:0x2a00000000069f": {
                        "SAI_TUNNEL_ATTR_DECAP_MAPPERS": "2:oid:0x2900000000069b,oid:0x2900000000069d",
                        "SAI_TUNNEL_ATTR_ENCAP_MAPPERS": "2:oid:0x2900000000069c,oid:0x2900000000069e",
                        "SAI_TUNNEL_ATTR_ENCAP_SRC_IP": "10.1.0.32",
                        "SAI_TUNNEL_ATTR_PEER_MODE": "SAI_TUNNEL_PEER_MODE_P2MP",
                        "SAI_TUNNEL_ATTR_TYPE": "SAI_TUNNEL_TYPE_VXLAN",
                        "SAI_TUNNEL_ATTR_UNDERLAY_INTERFACE": "oid:0x600000000056a"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069c": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VLAN_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069e": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VIRTUAL_ROUTER_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069b": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069d": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VIRTUAL_ROUTER_ID"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY:oid:0x2b0000000006a0": {
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_ACTION_TUNNEL_ID": "oid:0x2a00000000069f",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_DST_IP": "10.1.0.32",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TUNNEL_TYPE": "SAI_TUNNEL_TYPE_VXLAN",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE": "SAI_TUNNEL_TERM_TABLE_ENTRY_TYPE_P2MP",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID": "oid:0x3000000000002"
                    }
                }
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0x2a00000000069f": "oid:0x2a",
                "oid:0x2900000000069c": "oid:0x100000029",
                "oid:0x2900000000069e": "oid:0x300000029",
                "oid:0x2900000000069b": "oid:0x29",
                "oid:0x2900000000069d": "oid:0x200000029",
                "oid:0x2b0000000006a0": "oid:0x420000002b"
            }
        },
        "STATE_DB": {
            "keys": [],
            "tables_not_found": [
                "VXLAN_TUNNEL_TABLE"
            ]
        }
    }
}
```
```
dump state vxlan_tunnel_map all
{
    "vtep_1336|map_1336_Vlan2345": {
        "CONFIG_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL_MAP|vtep_1336|map_1336_Vlan2345": {
                        "vlan": "Vlan2345",
                        "vni": "1336"
                    }
                }
            ],
            "tables_not_found": []
        },
        "APPL_DB": {
            "keys": [
                {
                    "VXLAN_TUNNEL_MAP_TABLE:vtep_1336:map_1336_Vlan2345": {
                        "vlan": "Vlan2345",
                        "vni": "1336"
                    }
                }
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP_ENTRY:oid:0x3b0000000006a1": {
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_TUNNEL_MAP": "oid:0x2900000000069b",
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_TUNNEL_MAP_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID",
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_VLAN_ID_VALUE": "2345",
                        "SAI_TUNNEL_MAP_ENTRY_ATTR_VNI_ID_KEY": "1336"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x2900000000069b": {
                        "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID"
                    }
                }
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0x3b0000000006a1": "oid:0x10000003b",
                "oid:0x2900000000069b": "oid:0x29"
            }
        }
    }
}
```
```
dump state evpn 'Vlan2345:11.1.0.32'
{
    "Vlan2345:11.1.0.32": {
        "APPL_DB": {
            "keys": [
                {
                     "VXLAN_REMOTE_VNI_TABLE:Vlan2345:11.1.0.32": {
                         "vni": "1336"
                      }
                }
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                {
                        "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL:oid:0x2a0000000007e1": {
                             "SAI_TUNNEL_ATTR_UNDERLAY_INTERFACE": "oid:0x600000000056a",
                             "SAI_TUNNEL_ATTR_PEER_MODE": "SAI_TUNNEL_PEER_MODE_P2P",
                             "SAI_TUNNEL_ATTR_DECAP_MAPPERS": "2:oid:0x290000000007e9,oid:0x290000000007eb",
                             "SAI_TUNNEL_ATTR_ENCAP_SRC_IP": "10.1.0.32",
                             "SAI_TUNNEL_ATTR_ENCAP_DST_IP": "11.1.0.32",
                            "SAI_TUNNEL_ATTR_ENCAP_MAPPERS": "2:oid:0x290000000007ea,oid:0x290000000007ec",
                            "SAI_TUNNEL_ATTR_TYPE": "SAI_TUNNEL_TYPE_VXLAN"
                       },
                },
               {
                   "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY:oid:0x2b0000000007e1": {
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_ACTION_TUNNEL_ID": "oid:0x2a0000000007e1",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TUNNEL_TYPE": "SAI_TUNNEL_TYPE_VXLAN",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_VR_ID": "oid:0x3000000000010",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_DST_IP": "10.1.0.32",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_SRC_IP": "11.1.0.32",
                        "SAI_TUNNEL_TERM_TABLE_ENTRY_ATTR_TYPE": "SAI_TUNNEL_TERM_TABLE_ENTRY_TYPE_P2P"
                    }
                },
               {
                   "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007e9": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VLAN_ID"
                    }
                },
               {
                   "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007ec": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VIRTUAL_ROUTER_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007ea": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VLAN_ID_TO_VNI"
                    }
                },
                {
                    "ASIC_STATE:SAI_OBJECT_TYPE_TUNNEL_MAP:oid:0x290000000007eb": {
                          "SAI_TUNNEL_MAP_ATTR_TYPE": "SAI_TUNNEL_MAP_TYPE_VNI_TO_VIRTUAL_ROUTER_ID"
                    }
                }
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0x2a0000000007e1": "oid:0x2a",
                "oid:0x290000000007ec": "oid:0x100000029",
                "oid:0x290000000007eb": "oid:0x300000029",
                "oid:0x290000000007ea": "oid:0x29",
                "oid:0x290000000007e9": "oid:0x200000029",
                "oid:0x2b0000000007e1": "oid:0x420000002b"
            }
        },
        "STATE_DB": {
            "keys": [],
            "tables_not_found": [
                "VXLAN_TUNNEL_TABLE"
            ]
        }
    }
}
```

### CODE REVIEW

**Comment by dprital** [comment]
@prsunny  - Can you please review ?

**Review by prsunny — APPROVED** [review]

**Review by SuvarnaMeenakshi — APPROVED** [review]

**Review by SuvarnaMeenakshi — COMMENTED** [review]
Minor comment: https://github.com/Azure/sonic-utilities/blob/3641d350d19a2317bbe6a507da117e1ee24cc092/dump/plugins/evpn.py#L70 - line is too long , can be modified for readability.

**Comment by dgsudharsan** [comment]
> Minor comment:
> 
> https://github.com/Azure/sonic-utilities/blob/3641d350d19a2317bbe6a507da117e1ee24cc092/dump/plugins/evpn.py#L70
> 
> - line is too long , can be modified for readability.

Done

**Review by prsunny — APPROVED** [review]

**Review by SuvarnaMeenakshi — APPROVED** [review]

**Pull request merged**
