### PR TITLE
Add support for snat, dnat and ipmc crm resources

### PR DESCRIPTION
**Pull request by PrabhuSreenivasan**
Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>

**- What I did**
Added support for snat, dnat and ipmc resources under CRM module.

**- How I did it**
New feature NAT adds new resources snat_enty and dnat_entry that needs to be monitored. ipmc_entry tracks IP multicast resources used by switch.

**- How to verify it**
sonic-utilities tests and crm spytest

**- Associated PRs**
https://github.com/Azure/sonic-swss/pull/1511
https://github.com/Azure/sonic-buildimage/pull/6012

**- Previous command output (if the output of a command-line utility has changed)**
```

root@sonic:/home/admin# crm show thresholds all

Resource Name         Threshold Type      Low Threshold    High Threshold
--------------------  ----------------  ---------------  ----------------
ipv4_route            percentage                     70                85
ipv6_route            percentage                     70                85
ipv4_nexthop          percentage                     70                85
ipv6_nexthop          percentage                     70                85
ipv4_neighbor         percentage                     70                85
ipv6_neighbor         percentage                     70                85
nexthop_group_member  percentage                     70                85
nexthop_group         percentage                     70                85
acl_table             percentage                     70                85
acl_group             percentage                     70                85
acl_entry             percentage                     70                85
acl_counter           percentage                     70                85
fdb_entry             percentage                     70                85


root@sonic:/home/admin# crm show resources all

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                      54              32698
ipv6_route                       2              10238
ipv4_nexthop                     0              65460
ipv6_nexthop                     0              65460
ipv4_neighbor                    0              24576
ipv6_neighbor                    0              12288
nexthop_group_member             0              32768
nexthop_group                    0                256
fdb_entry                        0              65535


Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  3
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2


Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------
```
**- New command output (if the output of a command-line utility has changed)**
```
root@sonic:/home/admin# crm show thresholds all

Resource Name         Threshold Type      Low Threshold    High Threshold
--------------------  ----------------  ---------------  ----------------
ipv4_route            percentage                     70                85
ipv6_route            percentage                     70                85
ipv4_nexthop          percentage                     70                85
ipv6_nexthop          percentage                     70                85
ipv4_neighbor         percentage                     70                85
ipv6_neighbor         percentage                     70                85
nexthop_group_member  percentage                     70                85
nexthop_group         percentage                     70                85
acl_table             percentage                     70                85
acl_group             percentage                     70                85
acl_entry             percentage                     70                85
acl_counter           percentage                     70                85
fdb_entry             percentage                     70                85
ipmc_entry            percentage                     70                85
snat_entry            percentage                     70                85
dnat_entry            percentage                     70                85

root@sonic:/home/admin# crm show thresholds snat

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
snat_entry       percentage                     70                85

root@sonic:/home/admin# crm show thresholds dnat

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
dnat_entry       percentage                     70                85

root@sonic:/home/admin# crm show thresholds ipmc

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipmc_entry       percentage         

root@sonic:/home/admin# crm show resources snat

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
snat_entry                  0               1024

root@sonic:/home/admin# crm show resources dnat

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
dnat_entry                  0               1024

root@sonic:/home/admin# crm show resources ipmc

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipmc_entry                  0              24576

root@sonic:/home/admin# crm show resources all

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                      54              32698
ipv6_route                       2              10238
ipv4_nexthop                     0              65460
ipv6_nexthop                     0              65460
ipv4_neighbor                    0              24576
ipv6_neighbor                    0              12288
nexthop_group_member             0              32768
nexthop_group                    0                256
fdb_entry                        0              65535
ipmc_entry                       0              24576
snat_entry                       0               1024
dnat_entry                       0               1024


Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  3
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2


Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------
```

### CODE REVIEW

**Comment by lguohan** [comment]
please add unit tests accordingly.

**Comment by PrabhuSreenivasan** [comment]
> please add unit tests accordingly.

I have updated the PR with sonic-utilities test cases for the newly added resources.

**Review by lguohan — DISMISSED** [review]

**Review by lguohan — COMMENTED** [review]
i am wondering if there is no data in the db, what is the output, will the command throw exception?

**Comment by PrabhuSreenivasan** [comment]
> i am wondering if there is no data in the db, what is the output, will the command throw exception?

When no data on CONFIG_DB, crm show threshold CLI command will not have these resources listed.
When no data on COUNTERS_DB, crm show resources CLI command will not have these resources, instead will print

`CRM counters are not ready. They would be populated after the polling interval.`

No exception will be observed on both cases.

```
root@sonic:/home/admin# crm show thresholds all

Resource Name         Threshold Type      Low Threshold    High Threshold
--------------------  ----------------  ---------------  ----------------
ipv4_route            percentage                     70                85
ipv6_route            percentage                     70                85
ipv4_nexthop          percentage                     70                85
ipv6_nexthop          percentage                     70                85
ipv4_neighbor         percentage                     70                85
ipv6_neighbor         percentage                     70                85
nexthop_group_member  percentage                     70                85
nexthop_group         percentage                     70                85
acl_table             percentage                     70                85
acl_group             percentage                     70                85
acl_entry             percentage                     70                85
acl_counter           percentage                     70                85
fdb_entry             percentage                     70                85


root@sonic:/home/admin# crm show thresholds snat

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------


root@sonic:/home/admin# crm show thresholds dnat

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------


root@sonic:/home/admin# crm show thresholds ipmc

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------


root@sonic:/home/admin# crm show resources all

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                      65              32687
ipv6_route                       2              10238
ipv4_nexthop                     0              65476
ipv6_nexthop                     0              65476
ipv4_neighbor                    0              24576
ipv6_neighbor                    0              12288
nexthop_group_member             0              32768
nexthop_group                    0                256
fdb_entry                        0              65535


Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  3
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2


Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

root@sonic:/home/admin# crm show resources snat

CRM counters are not ready. They would be populated after the polling interval.
root@sonic:/home/admin# crm show resources dnat

CRM counters are not ready. They would be populated after the polling interval.
root@sonic:/home/admin# crm show resources ipmc

CRM counters are not ready. They would be populated after the polling interval.
        
```

**Comment by PrabhuSreenivasan** [comment]
retest this please

**Comment by ben-gale** [comment]
All, @arlakshm - this has been quiet for 6 days - can we get some review input so we can move forwards please? The clock is ticking ...

**Comment by ben-gale** [comment]
@arlakshm , @lguohan - What's the next step here? This has been inactive for 7 days now - how do we move towards merge pls?

**Review by arlakshm — APPROVED** [review]

**Comment by rlhui** [comment]
@ben-gale - fyi on a test failure which might be related to this PR - https://github.com/Azure/sonic-buildimage/issues/6302

**Pull request merged**
