### PR TITLE
[show/fgnhg.py] Fix whitespace issues

### PR DESCRIPTION
**Pull request by jleveque**
- Replace tabs with spaces
- Fix alignment
- Remove trailing whitespace
- Remove spaces where not necessary, add spaces where necessary
- Reorganize imports per PEP8 standards

### CODE REVIEW

**Comment by jleveque** [comment]
@kktheballer: Please review, and for future contributions, please ensure to use spaces instead of tabs.

**Comment by jleveque** [comment]
Retest this please

**Comment by kktheballer** [comment]
@jleveque Thank you so much for looking into the formatting and for making the changes. I will make sure to use spaces and watch out for unecessary whitespaces from now on. 

I believe one of the checks has failed. Let me try and rerun that first.

**Comment by kktheballer** [comment]
retest this please

**Comment by jleveque** [comment]
@kktheballer: Looking at the test failure, it appears that there is no V6 info in the output, but it is expected. Do you have an idea why?

**Comment by kktheballer** [comment]
@jleveque Let me take a look. Oddly, all the test cases were passing in the original PR.

**Comment by kktheballer** [comment]
retest this please

**Comment by lguohan** [comment]
the unit tests failed. likely due to the refactoring.

**Comment by jleveque** [comment]
> the unit tests failed. likely due to the refactoring.

That's my assumption, also. @kktheballer: Can you please review my changes, and check if I over- or under-indented a section?

**Review by lguohan — APPROVED** [review]

**Comment by kktheballer** [comment]
@jleveque Thanks for the indentation fix commit. Yes, it appeared that the issue was with the indentation level at which the table  was finally displaying values.

Will keep in mind about the formatting for next time.

**Pull request merged**
