### PR TITLE
sonic-installer: fix py3 issues in bootloader.aboot

### PR DESCRIPTION
**Pull request by Staphylo**
These issues are only seen on secureboot enabled platform.

### CODE REVIEW

**Comment by Staphylo** [comment]
I believe we also want this change to be cherry-picked on 202012

**Review by lguohan — APPROVED** [review]

**Comment by daall** [comment]
@staphylo there is a merge conflict cherry-picking to 202012 which I guess is probably because we don't have https://github.com/Azure/sonic-utilities/pull/1366 in 202012. Are those changes needed in the 202012 branch as well?

**Comment by Staphylo** [comment]
@dall I do believe we nee #1366 in 202012 as well.
Let me run some tests on 202012 and I'll confirm this back to you.

I can alternatively make a change against the 202012 branch that coalesce both changes.
Let me know what you prefer.

**Comment by Staphylo** [comment]
@daall I can confirm that both changes have to be backported.
Let me know if you need my help with anything.

**Comment by daall** [comment]
Thanks for confirming @staphylo, I will go ahead and cherry-pick both PRs to 202012! I'll let you know if I run into any problems.

**Pull request merged**
