### PR TITLE
Updated natshow script to support DNAT Pool changes

### PR DESCRIPTION
**Pull request by AkhileshSamineni**
Updated the natshow script to get the nat type from newly added attribute.

Depends on :
https://github.com/Azure/sonic-swss/pull/1358
https://github.com/Azure/sonic-sairedis/pull/644
https://github.com/Azure/sonic-swss-common/pull/367

Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by AkhileshSamineni** [comment]
Retest this please

**Comment by AkhileshSamineni** [comment]
@rlhui  @arlakshm  Could you please review and merge this PR.

**Review by arlakshm — APPROVED** [review]
lgtm

**Pull request merged**
