### PR TITLE
[202012] Add DHCPv6 Relay counter and ipv6 helper CLI

### PR DESCRIPTION
**Pull request by kellyyeh**
#### What I did
Add CLI support and tests for dhcp6relay show counter and ipv6 helpers
Updated commands in Command-Reference

#### How I did it
Add commands:
show dhcp6relay_counters counts
show dhcprelay_helper ipv6

#### How to verify it
Build an image with 202012 and test the commands

### CODE REVIEW

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
It is already on 202012 branch so no need to request.
I am wondering why you did not start on master branch, and cherry-pick to release branches?

**Comment by kellyyeh** [comment]
@qiluo-msft Sorry Qi, accidentally requested for 202012. DHCP Relay docker is made an extension for master and 202106 forward, and it carries the CLI plugin within the docker instead of in sonic-utilities.

**Pull request merged**
