### PR TITLE
Fix show interface status with LAG (202012 branch)

### PR DESCRIPTION
**Pull request by d-dashkov**
**- What I did**
Fixed crash of "show int status" command when there are portchannels in system.
fixes https://github.com/Azure/sonic-buildimage/issues/6816
It`s the same fix as for master https://github.com/Azure/sonic-utilities/pull/1376
```
Traceback (most recent call last):
  File "/usr/local/bin/intfutil", line 521, in <module>
    main()
  File "/usr/local/bin/intfutil", line 513, in main
    interface_stat.display_intf_status()
  File "/usr/local/bin/intfutil", line 354, in display_intf_status
    self.get_intf_status()
  File "/usr/local/lib/python3.7/dist-packages/utilities_common/multi_asic.py", line 137, in wrapped_run_on_all_asics
    func(self,  *args, **kwargs)
  File "/usr/local/bin/intfutil", line 435, in get_intf_status
    self.portchannel_speed_dict = po_speed_dict(self.po_int_dict, self.db)
  File "/usr/local/bin/intfutil", line 249, in po_speed_dict
    interface_speed = '{}G'.format(interface_speed[:-3])
TypeError: 'NoneType' object is not subscriptable
```

**- How I did it**
Added check of return value from db in inftutil.
If value is None, append N/A to the output instead of formatting incorrect type.

**- How to verify it**
1. Create portchannel
	$ sudo config portchannel add PortChannel0011
2. Add member
	$ config portchannel mem add PortChannel0011 Ethernet80
2. Execute interface status command
	$ show int status

Signed-off-by: d-dashkov <Dmytro_Dashkov@Jabil.com>

### CODE REVIEW

**Comment by d-dashkov** [comment]
@lguohan, could you review this PR? this is the same as for the master you have already merged (https://github.com/Azure/sonic-utilities/pull/1376)

**Comment by liat-grozovik** [comment]
@d-dashkov can the master fix cherry pick to 202012 or the solution is totally different?
in the case it can be cherry picked we can add a label to the original fix and ask the release maintainer to take it.

**Comment by d-dashkov** [comment]
@liat-grozovik the fix is totally same, it can be cherry picked

**Comment by liat-grozovik** [comment]
@d-dashkov it was taken care. Thanks @daall . You can close this PR.

**Pull request closed without merging**
