### PR TITLE
Use 'importlib' module in lieu of deprecated 'imp' module

### PR DESCRIPTION
**Pull request by jleveque**
#### What I did

Migrate from using the `imp` module to using the `importlib` module. As of Python 3, the `imp` module has been deprecated in favor of the `importlib` module.

Place logic in a new function, `load_module_from_source()` in a new file, `utilities_common/general.py`

Also fix some formatting

#### How I did it

Eliminate all importing of the `imp` module, and replace all which were actually used with imports of the `importlib` module, and modify all affected code appropriately.

#### How to verify it

Test all affected utilities and unit tests.

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Review by lguohan — APPROVED** [review]

**Comment by yxieca** [comment]
@jleveque this change cannot be cherry-picked cleanly. Do we need this change in 202012?

**Comment by jleveque** [comment]
@yxieca: It's not necessary, but recommended. I will look into creating a separate PR.

**Pull request merged**
