### PR TITLE
[sonic_sku_create] Add SKU creation support for Arista devices

### PR DESCRIPTION
**Pull request by lolyu**
#### What I did
Let's add Arista support to the SKU creator tool
**NOTE**: only creation from XML file is supported now

#### How I did it
Enable the SKU creator tool to parse Arista port alias

### CODE REVIEW

**Comment by yxieca** [comment]
@lolyu can you try this change against 7260? 7260 has 2 ports Ethernet256 and Ethernet260 that are not used. Would these 2 ports create any issue?

**Comment by lolyu** [comment]
> @lolyu can you try this change against 7260? 7260 has 2 ports Ethernet256 and Ethernet260 that are not used. Would these 2 ports create any issue?

@yxieca, sure, will add unittest to cover 7260.

**Review by yxieca — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by lolyu** [comment]
> This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

Sure, will do, thanks!

**Pull request merged**
