### PR TITLE
Add DHCPv6 Relay counter and ipv6 helper CLI

### PR DESCRIPTION
**Pull request by kellyyeh**
#### What I did
Add CLI support and tests for dhcp6relay show counter and ipv6 helpers

#### How I did it
Add commands:
show dhcp6relay_counters --counts
show dhcp6relay_counters --clear

show dhcprelay_helper ipv6

sonic-clear dhcp6relay_counters

#### How to verify it
Build an image with 202012 and test the commands

### CODE REVIEW

**Comment by yxieca** [comment]
> show dhcp6relay_counters --counts

This comment is not right. I think the code is right not requiring --counts. Can you confirm?

**Comment by Blueve** [comment]
Suggest use below command pattern:
```bash
show dhcp6relay counters
sonic-clear dhcp6relay counters 
# or
sonic-clear dhcp6relay-counters
```

And avoid add clear logic to `show` command. I think we suppose that `show` command will never have side effect.

**Comment by zhangyanxian** [comment]
Hi，kellyyeh, I am wondering why there isn't dhcp v4 relay counter? thank you~

**Comment by kellyyeh** [comment]
> Hi，kellyyeh, I am wondering why there isn't dhcp v4 relay counter? thank you~

We have dhcpmon to monitor DHCPv4 messages right now. We are planning to roll out our own DHCPv4 Relay which will include a counter with CLI

**Pull request closed without merging**
