### PR TITLE
[fwutil]: Fix component table layout

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

This PR contains a fix for component table layout
in case chassis/module has more than one component

**- What I did**
* Fixed component table layout

**- How I did it**
* N/A

**- How to verify it**
1. Show platform component status
```bash
show platform firmware
```
2. Run platform component automatic update
```bash
config platform firmware update
```

**- Previous command output (if the output of a command-line utility has changed)**
```bash
root@sonic:/home/admin# fwutil update
Error: ''. Aborting...
Aborted!
```

**- New command output (if the output of a command-line utility has changed)**
```bash
root@sonic:/home/admin# fwutil show status
Chassis                 Module    Component    Version                  Description
----------------------  --------  -----------  -----------------------  ----------------------------------------
x86_64-mlnx_msn3800-r0  N/A       BIOS         0ACLH004_02.02.007_9600  BIOS - Basic Input/Output System
                                  CPLD1        CPLD000000_REV0500       CPLD - Complex Programmable Logic Device
                                  CPLD2        CPLD000000_REV0300       CPLD - Complex Programmable Logic Device
                                  CPLD3        CPLD000000_REV0300       CPLD - Complex Programmable Logic Device
                                  CPLD4        CPLD000000_REV0100       CPLD - Complex Programmable Logic Device
```

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by nazariig** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by nazariig** [comment]
retest this please

**Comment by nazariig** [comment]
@jleveque please review & merge

**Pull request merged**
