### PR TITLE
[command reference] Update show int counters info with l3 RIF

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

**- What I did**
Updated command reference. Added info about show RIF counters commands.
**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by liat-grozovik** [comment]
retest please

**Comment by mykolaf** [comment]
retest default please

**Comment by mykolaf** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Pull request merged**
