### PR TITLE
[show] Fix int status of LAGs, configured as Vlan members

### PR DESCRIPTION
**Pull request by maksymbelei95**
Pass missed argument to function "appl_db_portchannel_status_get" in "intfutil" script to provide correct information in "Vlan" column of command "show int status" for LAG interfaces.

Signed-off-by: Maksym Belei <Maksym_Belei@jabil.com>

#### What I did
Resolves https://github.com/Azure/sonic-buildimage/issues/6928
Fixed status of LAG interfaces in Vlan column. LAG interfaces, configured as a Vlan member, should be seen as trunk interface.

#### How I did it
Missed argument "self.combined_int_to_vlan_po_dict" passed to function "appl_db_portchannel_status_get"
  in "intfutil" script.

#### How to verify it
```
admin@sonic:~$ show int status | grep PortChannel0011
      Ethernet4          4,5,6,7      N/A   9100    N/A     etp2  PortChannel0011    down       up             N/A         N/A
      Ethernet8        8,9,10,11      N/A   9100    N/A     etp3  PortChannel0011      up       up  QSFP+ or later         N/A
PortChannel0011              N/A        G   9100    N/A      N/A           routed    down       up             N/A         N/A
admin@sonic:~$ sudo config vlan member add 11 PortChannel0011
admin@sonic:~$ show vlan brief | grep 11
|        11 |              | PortChannel0011 | tagged         |                       | disabled    |
admin@sonic:~$ show int status | grep PortChannel0011
      Ethernet4          4,5,6,7      N/A   9100    N/A     etp2  PortChannel0011    down       up             N/A         N/A
      Ethernet8        8,9,10,11      N/A   9100    N/A     etp3  PortChannel0011      up       up  QSFP+ or later         N/A
PortChannel0011              N/A        G   9100    N/A      N/A            trunk    down       up             N/A         N/A
admin@sonic:~$ sudo config vlan member del 11 PortChannel0011
admin@sonic:~$ show vlan brief | grep 11
|        11 |              |         |                |                       | disabled    |
admin@sonic:~$ show int status | grep PortChannel0011
      Ethernet4          4,5,6,7      N/A   9100    N/A     etp2  PortChannel0011    down       up             N/A         N/A
      Ethernet8        8,9,10,11      N/A   9100    N/A     etp3  PortChannel0011      up       up  QSFP+ or later         N/A
PortChannel0011              N/A        G   9100    N/A      N/A           routed    down       up             N/A         N/A
```

### CODE REVIEW

**Review by prsunny — DISMISSED** [review]
lgtm

**Review by qiluo-msft — DISMISSED** [review]

**Comment by lguohan** [comment]
can you update the unit test?

**Review by lguohan — CHANGES_REQUESTED** [review]
need unit test

**Comment by maksymbelei95** [comment]
@lguohan, I have added changes in unit tests for intfutil to the PR.

**Review by qiluo-msft — DISMISSED** [review]

**Comment by qiluo-msft** [comment]
@maksymbelei95 Is this PR needed on 201911 branch?

**Comment by maksymbelei95** [comment]
@qiluo-msft, the issue is being occurred on master and 202012 branches, but, did not checked on 201911. I will check and let you know whether the PR is needed on 201911.

**Comment by qiluo-msft** [comment]
Thanks for checking!

**Review by prsunny — APPROVED** [review]

**Comment by maksymbelei95** [comment]
@qiluo-msft, regarding 201911. The related line of script `intfutil `looks right:
https://github.com/Azure/sonic-utilities/blob/201911/scripts/intfutil#L402
I think there is no need to cherry-pick the PR to 201911.

**Review by liat-grozovik — DISMISSED** [review]

**Comment by qiluo-msft** [comment]
@lguohan Could you help review again? Unit test was added.

**Comment by maksymbelei95** [comment]
@lguohan, could you review the PR?

**Comment by prsunny** [comment]
@maksymbelei95 , would you please resolve conflict?

**Comment by maksymbelei95** [comment]
@prsunny, done.

**Review by qiluo-msft — APPROVED** [review]

**Comment by maksymbelei95** [comment]
@prsunny, could you merge the PR?

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@maksymbelei95 could you please update submodule to get the fix in master?

**Comment by maksymbelei95** [comment]
@liat-grozovik, created PR with the submodule update: https://github.com/Azure/sonic-buildimage/pull/7144

**Pull request merged**
