### PR TITLE
[vrf] change management vrf config commands

### PR DESCRIPTION
**Pull request by tylerlinp**
**- What I did**
Change management vrf config commands from `config vrf add/del mgmt` to `config mgmt-vrf add/del`.
Because vrf commands and mgmt-vrf commands conflict, mgmt-vrf cannot config now.
In mgmt-vrf add command not only create vrf mgmt but also move eth0, it is different from general vrf, so I think it is better to keep seperate CLIs, just like `show mgmt-vrf`.

**- How I did it**

**- How to verify it**
Config these commands manually and check results.

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by tylerlinp** [comment]
retest this please

**Comment by tylerlinp** [comment]
retest this please

**Comment by tylerlinp** [comment]
retest this please

**Comment by tylerlinp** [comment]
retest this please

**Comment by tylerlinp** [comment]
retest this please

**Comment by kannankvs** [comment]
@tylerlinp : Management VRF commands were earlier reviewed and decided to use same command for management VRF and data VRF. It was decided to use "mgmt" or "management" as the fixed VRF name to differentiate the management VRF. In the recent data VRF merge, this command "config vrf" has been duplicated, due to which the management VRF configuration is missing. A new [PR759](https://github.com/Azure/sonic-utilities/pull/759) has been raised to resolve it. I think that we should merge PR759 and ignore this PR760.

**Comment by tylerlinp** [comment]
@kannankvs I think both are all right. Let reviwers make a decision.

**Comment by prsunny** [comment]
@tylerlinp , i think this is fixed as part of #759, if you agree, can u close this?

**Comment by tylerlinp** [comment]
ok

**Pull request closed without merging**
