### PR TITLE
Azure 277

### PR DESCRIPTION
**Pull request by madhupalu**
commit c71894370394fbda51635b2a549169cfde829217 (HEAD -> azure-277)
Author: madhu Pal <madhupa@aviznetworks.com>
Date:   Wed Jan 30 04:20:26 2019 +0000

    [config/main.py] Fixed typo in passing arguments -port_namee (#277)

    Signed-off-by: madhu Pal <madhupa@aviznetworks.com>

### CODE REVIEW

**Comment by madhupalu** [comment]
Prince,  
Could you help me to resolve the merge conflicts. 
Thanks
-Madhu

**Comment by stcheng** [comment]
Could you change the pull request title?

**Comment by prsunny** [comment]
You can close this PR and create a new one with the fix and also the test results. As Shuotian mentioned, please use appropriate title for the PRs with command and test outputs

**Comment by madhupalu** [comment]
Sure. 
one quick question - how can I raise pull request with changes spread across multiple repos ex: sonic-utilties & sonic-py-swsssdk? shall we raise two pull requests or combined one? if combined one how can we do?

**Comment by prsunny** [comment]
You should raise two pull-requests and specify in PR if it is dependent on other. This way, merge can wait until the dependent PR is approved and merged.

**Pull request closed without merging**
