### PR TITLE
[Bug]: Fix show ip bgp nei command rw required issue

### PR DESCRIPTION
**Pull request by xumia**
#### What I did
Fix the ro command rw permission required issue
```
show ip bgp neighbors 

Make sure your account has RW permission to current device.
Otherwise sudo requests will be rejected.
```

### CODE REVIEW

**Comment by ghooo** [comment]
Build failure should be fixed by https://github.com/Azure/sonic-utilities/pull/2012

**Review by qiluo-msft — APPROVED** [review]

**Comment by SuvarnaMeenakshi** [comment]
@vperumal fyi

**Pull request merged**
