### PR TITLE
[storyteller] allow storyteller to work on downloaded logs

### PR DESCRIPTION
**Pull request by yxieca**
**- What I did**

- Add log path parameter to allow storyteller to work on  logs downloaded from sonic devices.
- Improve reboot regex to capture more warm reboot related logs.

**- How to verify it**
Use storyteller against a sonic dump.

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

### CODE REVIEW

**Comment by yxieca** [comment]
retest this please

**Comment by yxieca** [comment]
retest this please

**Comment by neethajohn** [comment]
> retest this please
Fix for the vs test failures is in review. #1390

**Comment by yxieca** [comment]
retest this please

**Review by jleveque — APPROVED** [review]

**Pull request merged**
