### PR TITLE
Support sub port interface admin status change

### PR DESCRIPTION
**Pull request by wendani**
**- What I did**
Implement HLD https://github.com/Azure/SONiC/pull/420

**- How I did it**

**- How to verify it**
On mlnx dut

alias mode:
```
$ show  interfaces naming_mode
alias
```
```
$ sudo config interface shutdown etp17.10

$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) "admin_status"
2) "down"

$ redis-cli -n 0 hgetall "INTF_TABLE:Ethernet64.10"
1) "admin_status"
2) "down"
```
```
$ sudo config interface startup etp17.10

$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) "admin_status"
2) "up"

$ redis-cli -n 0 hgetall "INTF_TABLE:Ethernet64.10"        
1) "admin_status"
2) "up"
```

default mode:
```
$ show interfaces naming_mode 
default
```
```
$ sudo config interface shutdown Ethernet64.10

$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) "admin_status"
2) "down"

$ redis-cli -n 0 hgetall "INTF_TABLE:Ethernet64.10"
1) "admin_status"
2) "down"
```
```
$ sudo config interface startup Ethernet64.10

$ redis-cli -n 4 hgetall "VLAN_SUB_INTERFACE|Ethernet64.10"
1) "admin_status"
2) "up"

$ redis-cli -n 0 hgetall "INTF_TABLE:Ethernet64.10"
1) "admin_status"
2) "up"
```
**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

-->

### CODE REVIEW

**Comment by wendani** [comment]
retest this please

**Comment by wendani** [comment]
retest this please

**Comment by prsunny** [comment]
Is this [PR](https://github.com/Azure/sonic-utilities/pull/651/files) a super set of this one?

**Comment by wendani** [comment]
Yes. https://github.com/Azure/sonic-utilities/pull/638#issuecomment-532920388

**Pull request merged**
