### PR TITLE
[counterpoll] Add new FC group for port buffer drop counters.

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

Add new FC group for port buffer drop counters.

See https://github.com/Azure/sonic-buildimage/pull/5093
**- What I did**

**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by mykolaf** [comment]
retest default please

**Comment by mykolaf** [comment]
retest default please

**Comment by mykolaf** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
need unit test for the newly added feature.

**Comment by daall** [comment]
@mykolaf can this be cherry-picked in via #1009?

**Comment by mykolaf** [comment]
> @mykolaf can this be cherry-picked in via #1009?

@daall No, due to rename of `sonic-utilities-tests` -> `test` I believe this does not apply cleanly. Or if it applies, the `mock_tables` is only updated in the old folder.

**Pull request merged**
