### PR TITLE
[multi-ASIC]  CRM show/config commands changes for multi-asic

### PR DESCRIPTION
**Pull request by judyjoseph**
**- What I did**
Updated the CRM show/config commands to handle the multi-ASIC platforms.

**- How I did it**
The threshold setting configured by user is programmed in the CONFIG_DB in all the namespaces.  While displaying the thresholds, it is retrieved from the database docker in case of single asic, and from the first namespace docker eg: database0 in case of multi-asic platforms. 

The other resources are retrieved from the databases in the respective namespaces and displayed with the  additional ASIC name header.

**- How to verify it**
Verified on the single and multi-asic devices. 

**- Previous command output (if the output of a command-line utility has changed)**

There is no change to the earlier commands in single ASIC. In multi ASIC there will be multiple rows with ASIC name as part of the header.

**- New command output (if the output of a command-line utility has changed)**

```

==========================
Multi ASIC device
==========================

admin@str--acs-1:~$ crm show resources all

ASIC0

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6423              91881
ipv6_route                    6407               9977
ipv4_nexthop                     3              49146
ipv6_nexthop                     1              49146
ipv4_neighbor                    3               8187
ipv6_neighbor                    1               4093
nexthop_group_member             2              16382
nexthop_group                    1                255
fdb_entry                        0              32767


ASIC1

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6423              91881
ipv6_route                       6              16378
ipv4_nexthop                     3              49147
ipv6_nexthop                     0              49147
ipv4_neighbor                    3               8189
ipv6_neighbor                    0               4094
nexthop_group_member             2              16382
nexthop_group                    1                255
fdb_entry                        0              32767


ASIC2

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6431              91873
ipv6_route                      13              16371
ipv4_nexthop                     2              49148
ipv6_nexthop                     0              49148
ipv4_neighbor                    2               8190
ipv6_neighbor                    0               4095
nexthop_group_member             2              16382
nexthop_group                    1                255
fdb_entry                        0              32767


ASIC3

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6431              91873
ipv6_route                      14              16370
ipv4_nexthop                     2              49148
ipv6_nexthop                     0              49148
ipv4_neighbor                    2               8190
ipv6_neighbor                    0               4095
nexthop_group_member             2              16382
nexthop_group                    1                255
fdb_entry                        0              32767


ASIC4

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6422              91882
ipv6_route                       3              16381
ipv4_nexthop                     4              49146
ipv6_nexthop                     0              49146
ipv4_neighbor                    4               8188
ipv6_neighbor                    0               4094
nexthop_group_member             0              16384
nexthop_group                    0                256
fdb_entry                        0              32767


ASIC5

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6422              91882
ipv6_route                       3              16381
ipv4_nexthop                     4              49146
ipv6_nexthop                     0              49146
ipv4_neighbor                    4               8188
ipv6_neighbor                    0               4094
nexthop_group_member             0              16384
nexthop_group                    0                256
fdb_entry                        0              32767


ASIC0

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                254
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                   2                254
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                254
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                254
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                254
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                254
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                254
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                254
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                254
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                254
EGRESS   SWITCH        acl_table                   0                  2


ASIC1

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                254
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                   2                254
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                254
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                254
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                254
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                254
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                254
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                254
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                254
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                254
EGRESS   SWITCH        acl_table                   0                  2


ASIC2

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                246
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                  10                246
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                246
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                246
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                246
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                246
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                246
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                246
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                246
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                246
EGRESS   SWITCH        acl_table                   0                  2


ASIC3

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                246
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                  10                246
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                246
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                246
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                246
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                246
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                246
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                246
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                246
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                246
EGRESS   SWITCH        acl_table                   0                  2


ASIC4

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  4
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  4
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2


ASIC5

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  4
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  4
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2


ASIC0

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC1

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC2

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC3

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC4

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC5

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

admin@str--acs-1:~$ crm show resources fdb

ASIC0

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767


ASIC1

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767


ASIC2

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767


ASIC3

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767


ASIC4

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767


ASIC5

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767

admin@str--acs-1:~$ crm show resources ipv4 route

ASIC0

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6423              91881


ASIC1

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6423              91881


ASIC2

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6431              91873


ASIC3

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6431              91873


ASIC4

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6422              91882


ASIC5

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6422              91882
  
admin@str--acs-1:~$ crm show resources ipv6 nexthop 

ASIC0

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop                1              49146


ASIC1

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop                0              49147


ASIC2

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop                0              49148


ASIC3

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop                0              49148


ASIC4

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop                0              49146


ASIC5

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop                0              49146

admin@str--acs-1:~$ crm show resources acl group 

ASIC0

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                254
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                   2                254
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                254
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                254
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                254
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                254
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                254
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                254
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                254
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                254
EGRESS   SWITCH        acl_table                   0                  2


ASIC1

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                254
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                   2                254
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                254
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                254
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                254
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                254
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                254
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                254
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                254
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                254
EGRESS   SWITCH        acl_table                   0                  2


ASIC2

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                246
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                  10                246
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                246
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                246
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                246
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                246
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                246
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                246
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                246
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                246
EGRESS   SWITCH        acl_table                   0                  2


ASIC3

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                246
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                  10                246
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                246
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                246
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                246
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                   0                246
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                246
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                246
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                246
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                246
EGRESS   SWITCH        acl_table                   0                  2


ASIC4

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  4
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  4
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2


ASIC5

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                   0                256
INGRESS  PORT          acl_table                   0                  4
INGRESS  LAG           acl_group                   0                256
INGRESS  LAG           acl_table                   0                  4
INGRESS  VLAN          acl_group                   0                256
INGRESS  VLAN          acl_table                   0                  9
INGRESS  RIF           acl_group                   0                256
INGRESS  RIF           acl_table                   0                  9
INGRESS  SWITCH        acl_group                   0                256
INGRESS  SWITCH        acl_table                   0                  9
EGRESS   PORT          acl_group                   0                256
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                256
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                256
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                256
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                256
EGRESS   SWITCH        acl_table                   0                  2

admin@str--acs-1:~$ crm show resources acl table

ASIC0

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC1

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC2

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC3

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC4

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------


ASIC5

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

admin@str--acs-1:~$ crm show thresholds all

Resource Name         Threshold Type      Low Threshold    High Threshold
--------------------  ----------------  ---------------  ----------------
ipv4_route            percentage                     70                85
ipv6_route            percentage                     70                85
ipv4_nexthop          percentage                     70                85
ipv6_nexthop          percentage                     70                85
ipv4_neighbor         percentage                     70                85
ipv6_neighbor         percentage                     70                85
nexthop_group_member  percentage                     70                85
nexthop_group         percentage                     70                85
acl_table             percentage                     70                85
acl_group             percentage                     70                99
acl_entry             percentage                     70                85
acl_counter           percentage                     70                85
fdb_entry             percentage                     70                85

admin@str--acs-1:~$ crm show thresholds fdb

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
fdb_entry        percentage                     70                85

admin@str--acs-1:~$ crm show summary 

Polling Interval: 500 second(s)


==========================
Single ASIC device
==========================

admin@str-s6000-acs-8:~$ crm show thresholds acl table 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
acl_table        percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds acl group 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
acl_group        percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds all

Resource Name         Threshold Type      Low Threshold    High Threshold
--------------------  ----------------  ---------------  ----------------
ipv4_route            percentage                     70                85
ipv6_route            percentage                     70                85
ipv4_nexthop          percentage                     70                85
ipv6_nexthop          percentage                     70                85
ipv4_neighbor         percentage                     70                85
ipv6_neighbor         percentage                     70                85
nexthop_group_member  percentage                     70                85
nexthop_group         percentage                     70                85
acl_table             percentage                     70                85
acl_group             percentage                     70                85
acl_entry             percentage                     70                85
acl_counter           percentage                     70                85
fdb_entry             percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds fdb

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
fdb_entry        percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv4 neighbor 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv4_neighbor    percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv4 nexthop 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv4_nexthop     percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv4 route

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv4_route       percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv4 nexthop 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv4_nexthop     percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv4 neighbor 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv4_neighbor    percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv6 route 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv6_route       percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv6 neighbor 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv6_neighbor    percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds ipv6 nexthop 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
ipv6_nexthop     percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds nexthop group member 

Resource Name         Threshold Type      Low Threshold    High Threshold
--------------------  ----------------  ---------------  ----------------
nexthop_group_member  percentage                     70                85

admin@str-s6000-acs-8:~$ crm show thresholds nexthop group object 

Resource Name    Threshold Type      Low Threshold    High Threshold
---------------  ----------------  ---------------  ----------------
nexthop_group    percentage                     70                85

admin@str-s6000-acs-8:~$ crm show resources acl group 

Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                  32                184
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                   8                184
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                184
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                184
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                184
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                  32                184
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                184
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                184
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                184
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                184
EGRESS   SWITCH        acl_table                   0                  2

admin@str-s6000-acs-8:~$ crm show resources acl table

Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

admin@str-s6000-acs-8:~$ crm show resources all 

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
ipv4_route                    6475              91829
ipv6_route                    6476               9908
ipv4_nexthop                    24              49102
ipv6_nexthop                    24              49102
ipv4_neighbor                   24               8120
ipv6_neighbor                   24               4060
nexthop_group_member            51              16333
nexthop_group                    8                504
fdb_entry                        0              32767


Stage    Bind Point    Resource Name      Used Count    Available Count
-------  ------------  ---------------  ------------  -----------------
INGRESS  PORT          acl_group                  32                184
INGRESS  PORT          acl_table                   2                  3
INGRESS  LAG           acl_group                   8                184
INGRESS  LAG           acl_table                   0                  3
INGRESS  VLAN          acl_group                   0                184
INGRESS  VLAN          acl_table                   0                  6
INGRESS  RIF           acl_group                   0                184
INGRESS  RIF           acl_table                   0                  6
INGRESS  SWITCH        acl_group                   0                184
INGRESS  SWITCH        acl_table                   0                  6
EGRESS   PORT          acl_group                  32                184
EGRESS   PORT          acl_table                   0                  2
EGRESS   LAG           acl_group                   0                184
EGRESS   LAG           acl_table                   0                  2
EGRESS   VLAN          acl_group                   0                184
EGRESS   VLAN          acl_table                   0                  2
EGRESS   RIF           acl_group                   0                184
EGRESS   RIF           acl_table                   0                  2
EGRESS   SWITCH        acl_group                   0                184
EGRESS   SWITCH        acl_table                   0                  2


Table ID    Resource Name    Used Count    Available Count
----------  ---------------  ------------  -----------------

admin@str-s6000-acs-8:~$ crm show resources fdb

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
fdb_entry                   0              32767

admin@str-s6000-acs-8:~$ crm show resources ipv4 route 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_route               6475              91829

admin@str-s6000-acs-8:~$ crm show resources ipv4 neighbor 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_neighbor              24               8120

admin@str-s6000-acs-8:~$ crm show resources ipv4 nexthop 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv4_nexthop               24              49102

admin@str-s6000-acs-8:~$ crm show resources ipv6 nexthop 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_nexthop               24              49102

admin@str-s6000-acs-8:~$ crm show resources ipv6 neighbor 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_neighbor              24               4060

admin@str-s6000-acs-8:~$ crm show resources ipv6 route 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
ipv6_route               6476               9908

admin@str-s6000-acs-8:~$ crm show resources nexthop group member 

Resource Name           Used Count    Available Count
--------------------  ------------  -----------------
nexthop_group_member            51              16333

admin@str-s6000-acs-8:~$ crm show resources nexthop group object 

Resource Name      Used Count    Available Count
---------------  ------------  -----------------
nexthop_group               8                504

### CODE REVIEW

**Comment by judyjoseph** [comment]
@arlakshm , @jleveque  Please share your comments

**Comment by lguohan** [comment]
please add unit test accordingly.

**Review by lguohan — CHANGES_REQUESTED** [review]
add unit test accordingly.

**Comment by judyjoseph** [comment]
retest this please

**Comment by judyjoseph** [comment]
retest this please

**Comment by judyjoseph** [comment]
@lguohan @arlakshm @jleveque could you take a look ?

**Comment by judyjoseph** [comment]
Thanks Joe , @prsunny please take a look !

**Review by prsunny — DISMISSED** [review]
lgtm, please provide a sample output of single ASIC

Thanks Prince, updated the output of single ASIC device as well in the PR description.

**Comment by lguohan** [comment]
crm/main.py	310	39	0	87%

i can still see some function not covered. can you cover those? improve to 95%+?

**Comment by judyjoseph** [comment]
> crm/main.py 310 39 0 87%
> 
> i can still see some function not covered. can you cover those? improve to 95%+?

Added more unit tests, the coverage now stands at 
**crm/main.py                                  317     14    96%**

**Comment by judyjoseph** [comment]
retest this please

**Review by prsunny — APPROVED** [review]

**Review by lguohan — APPROVED** [review]

**Pull request merged**
