### PR TITLE
[show] add support for hwstatus in show muxcable status

### PR DESCRIPTION
**Pull request by vdahiya12**
Signed-off-by: vaibhav-dahiya <vdahiya@microsoft.com>

#### What I did
This PR supports for muxcable status command to support HWSTATUS as well.
the HWSTATUS could be either of these values
consistent/inconsistent/absent/Not-Y-Cable-Port/unknown

#### How I did it
Made the changes in both sonic-platform-daemons as well as sonic-utilities. 
This PR is dependent on https://github.com/Azure/sonic-platform-daemons/pull/219

#### How to verify it
Ran the changes on Arista7260cx3 platform as well as unit-tests
#### New command output (if the output of a command-line utility has changed)

```
admin@sonic:~$ show mux status
PORT         STATUS    HEALTH     HWSTATUS    LAST_SWITCHOVER_TIME
-----------  --------  ---------  ----------  ---------------------------
Ethernet0    active    unhealthy  consistent  2022-Mar-14 19:40:06.851394
Ethernet4    active    unhealthy  consistent  2022-Mar-14 19:40:06.863977
Ethernet8    active    unhealthy  consistent  2022-Mar-14 19:40:06.867504
Ethernet12   active    unhealthy  consistent  2022-Mar-14 19:40:07.149011
Ethernet16   active    unhealthy  consistent  2022-Mar-14 19:40:07.179085
Ethernet20   active    unhealthy  consistent  2022-Mar-14 19:40:07.174677
Ethernet40   active    healthy    consistent  2022-Mar-14 19:40:07.264452
Ethernet44   active    healthy    consistent  2022-Mar-14 19:40:07.452626
Ethernet48   active    unhealthy  consistent  2022-Mar-14 19:40:07.511005
Ethernet52   active    unhealthy  consistent  2022-Mar-14 19:40:07.644608
Ethernet56   active    unhealthy  consistent  2022-Mar-14 19:40:07.630628
Ethernet60   active    unhealthy  consistent  2022-Mar-14 19:40:07.739968
Ethernet64   active    unhealthy  consistent  2022-Mar-14 19:40:07.784666
Ethernet68   active    healthy    consistent  2022-Mar-14 19:40:07.728138
Ethernet72   active    healthy    consistent  2022-Mar-14 19:40:07.901363
Ethernet76   active    healthy    consistent  2022-Mar-14 19:40:07.957279
Ethernet80   active    healthy    consistent  2022-Mar-14 19:40:08.011392
Ethernet84   active    healthy    consistent  2022-Mar-14 19:40:08.149346
Ethernet104  active    healthy    consistent  2022-Mar-14 19:40:09.312243
Ethernet108  active    healthy    consistent  2022-Mar-14 19:40:09.312293
Ethernet112  active    healthy    consistent  2022-Mar-14 19:40:09.313652
Ethernet116  active    healthy    consistent  2022-Mar-14 19:40:09.313820
Ethernet120  active    healthy    consistent  2022-Mar-14 19:40:09.318580
Ethernet124  standby   unhealthy  consistent  2022-Mar-14 19:43:57.893061
```

### CODE REVIEW

**Review by prgeor — DISMISSED** [review]
@vdahiya12 do we have any design document for these muxcable related configuration and CLI?

**Review by zjswhhh — APPROVED** [review]
Looks good to me!

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Pull request merged**
