### PR TITLE
[CLI][PFCWD][Multi-ASIC] Added multi ASIC support to 'pfcwd' CLI

### PR DESCRIPTION
**Pull request by smaheshm**
**- What I did**

Merged following from master into 201911:

#1085 [pfcwd] Add single asic unit tests for show commands
#1080 [CLI][PFCWD][Multi-ASIC] Added multi ASIC support to 'pfcwd' CLI

**- How I did it**
Manual merge

**- How to verify it**
Unit tests

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by neethajohn** [comment]
Can you fix the LGTM alerts?

**Comment by smaheshm** [comment]
looking into import issues.

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
retest this please

**Comment by smaheshm** [comment]
retest this please

**Review by abdosi — APPROVED** [review]

**Pull request merged**
