### PR TITLE
Management vrf snmp cli support

### PR DESCRIPTION
**Pull request by vharish02**
CLI commands for configuring few parameters that are required in snmpd.conf.
1) "snmpd" daemon (snmp agent) shall use this configured IP address and VRF to listen on the particular IP address on that particular VRF.
2) "snmpd" daemon shall use the configured TRAP IP address and VRF to send the TRAPs to those servers connected in that particular VRF.
Requried back end snmpd patches are already applied in sonic-buildimage to handle this additional "VRF" configuration.

**Configuration**  
root@sonic:# config vrf add mgmt
root@sonic:# config snmpagentaddress add 100.104.45.9 -v mgmt
root@sonic:# config snmptrap modify 3 100.94.212.7 -v mgmt
root@sonic:# cat /etc/sonic/snmp.yml
snmp_rocommunity: public
snmp_location: public
v1_trap_dest: NotConfigured
v2_trap_dest: NotConfigured
v3_trap_dest: 100.94.212.7:162%mgmt public
snmp_agent_address_1: 100.104.45.9%mgmt

root@sonic:~# docker exec -it snmp bash
The file /etc/snmp/snmpd.conf inside snmp docker shows the following configuration which will be used by snmpd daemon.
Following  %mgmt will be used by snmpd to listen to the IP 100.104.45.9 in "mgmt" vrf.
agentAddress 100.104.45.9%mgmt  

Following %mgmt will be used by snmpd to send traps to the server 100.94.212.7 in "mgmt" vrf.
informsink 100.94.212.7:162%mgmt public

### CODE REVIEW

**Comment by a-barboza** [comment]
Are the changes for SNMP CLI described anywhere ?
Can we add additional folks to review ?

**Comment by kannankvs** [comment]
@jleveque : We will resolve conflict for the PR after the main mvrf SNMP [PR2608](https://github.com/Azure/sonic-buildimage/pull/2608) is merged. Let us wait until then.

**Comment by kannankvs** [comment]
@a-barboza : We will be explaining these CLIs in the CLI reference manual. If you need the same information to be filled in this PR, let us know.

**Comment by a-barboza** [comment]
1. Why restart NTP ?  (These changes are for SNMP ?)

2. clear_mgmt command: There are some new commands common to all mgmt-vrf ?  
    MGMT_INTERFACE, MGMT_VRF_CONFIG tables ?

3. There is a new "--gw" option? Why is this only for eth0 ? Can Front Panel (In-Band) port be part of the mgmt-vrf ? 

4. Is the table #1001 reserved for mgmt-vrf, or is it Table# 1 ?

5.  In snmpagentaddress why is the get_entry() there? Is it a No-OP ?

6. Is the  Curl, Wget, SSH  also supported for mgmt-vrf ?

**Comment by kannankvs** [comment]
@a-barboza : We shall look into this PR after we merge the [PR463](https://github.com/Azure/sonic-utilities/pull/463). Request you to kindly review the 463 and provide the comments.

**Comment by kannankvs** [comment]
@a-barboza : Reg Q5 "In snmpagentaddress why is the get_entry() there? Is it a No-OP ?", 
I assume u meant the following line that is present before set_entry for SNMP_AGENT_ADDRESS_CONFIG.
config_db.get_entry('SNMP_AGENT_ADDRESS_CONFIG', (agentip, vrf))
This No-OP line shall be removed.

**Comment by kannankvs** [comment]
This PR has dependency on [PR3586](https://github.com/Azure/sonic-buildimage/pull/3586) for handling these config change in the backend. Request you to merge this after the PR3586 is merged.

**Comment by kannankvs** [comment]
**Configuration**  
root@sonic:# config vrf add mgmt
root@sonic:# config snmpagentaddress add 100.104.45.9 -v mgmt
root@sonic:# config snmptrap modify 3 100.94.212.7 -v mgmt
root@sonic:# cat /etc/sonic/snmp.yml
snmp_rocommunity: public
snmp_location: public
v1_trap_dest: NotConfigured
v2_trap_dest: NotConfigured
v3_trap_dest: 100.94.212.7:162%mgmt public
snmp_agent_address_1: 100.104.45.9%mgmt

root@sonic:~# docker exec -it snmp bash
The file "docker exec -it snmp bash" inside snmp docker shows the following configuration which will be used by snmpd daemon.
agentAddress 100.104.45.9%mgmt
informsink 100.94.212.7:162%mgmt public

**Comment by kannankvs** [comment]
Dependent [PR3586](https://github.com/Azure/sonic-buildimage/pull/3586) is merged. Request the reviewers to review this PR.
One build is failing w.r.t. FRR which is nothing related to this PR. Can it be restarted?

**Comment by kannankvs** [comment]
retest please

**Comment by kannankvs** [comment]
retest this please

**Comment by kannankvs** [comment]
@jleveque, @prsunny  : Now that the code freeze deadline is nearing, can you review this and provide comments?

**Pull request merged**
