### PR TITLE
[nvgre] Added auto-generated CLI plugins and test for NVGRE Tunnel feature

### PR DESCRIPTION
**Pull request by vadymhlushko-mlnx**
***DEPENDS ON: [[nvgre] Added YANG model and tests #10095](https://github.com/Azure/sonic-buildimage/pull/10095)***
because the UT will not pass without the YANG model.

#### What I did
Added a click CLI plugins for NVGRE Tunnel feature

#### How I did it
The CLI plugins were auto-generated (by using the `sonic-cli-gen`) for the `show` and `config` CLI groups.

#### How to verify it
Added UT.

### CODE REVIEW

**Comment by vadymhlushko-mlnx** [comment]
@kperumalbfn could you please help to review?

**Review by volodymyrsamotiy — APPROVED** [review]

**Review by volodymyrsamotiy — APPROVED** [review]

**Review by liat-grozovik — APPROVED** [review]

**Pull request merged**
