### PR TITLE
[201911]  CRM show/config commands changes for multi-asic (#1127)

### PR DESCRIPTION
**Pull request by judyjoseph**
Including CRM changes in 201911 branch, https://github.com/Azure/sonic-utilities/pull/1127

### CODE REVIEW

**Comment by judyjoseph** [comment]
@abdosi , please wait for a while before merge.
There are pytest changes I have to still commit ( diff between master & 201911 )

**Comment by jleveque** [comment]
Retest this please

**Comment by judyjoseph** [comment]
@abdosi, Please take this PR into 201911 - I have verified that the unit tests were passing locally - thanks !

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
@judyjoseph: FYI, yesterday I added support to sonic-utilities to properly test PRs created against the 201911 branch.

**Comment by judyjoseph** [comment]
> @judyjoseph: FYI, yesterday I added support to Jenkins to properly test sonic-utilities PRs created against the 201911 branch.

Okay thanks Joe, will check the results then !

**Comment by jleveque** [comment]
Retest this please

**Comment by judyjoseph** [comment]
@jleveque , the unit tests are passing .. it seems to be failing here, 
```
14:54:33  [htmlpublisher] Archiving at BUILD level /data/johnar/workspace/common/sonic-utilities-build-pr@2/sonic-utilities/htmlcov to /var/jenkins_home/jobs/common/jobs/sonic-utilities-build-pr/builds/3129/htmlreports/RCov_20Report
14:54:33  ERROR: Specified HTML directory '/data/johnar/workspace/common/sonic-utilities-build-pr@2/sonic-utilities/htmlcov' does not exist.
14:54:33  [Pipeline] publishCoverage (hide)
14:54:33  Publishing Coverage report....
14:54:33  No reports were found
```

Have you seen this error ? Could you check please ....

**Comment by jleveque** [comment]
@judyjoseph: That's a symptom, not the problem. It looked like a Jenkins issue. I retested again. We'll see...

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by judyjoseph** [comment]
> Retest this please

thanks @jleveque the tests pass now , @abdosi can you merge in for next build

**Comment by judyjoseph** [comment]
retest this please

**Review by abdosi — APPROVED** [review]
I think build failure is un-related. Merging this.

**Pull request merged**
