### PR TITLE
[sfpshow][mock_state_db] Tweak key names of some transceiver info fields

### PR DESCRIPTION
**Pull request by jleveque**
Change the following key names:

- hardwarerev -> hardware_rev
- serialnum -> serial
- manufacturename -> manufacturer
- modelname -> model
- Connector -> connector

Depends on:
- https://github.com/Azure/sonic-platform-common/pull/97
- https://github.com/Azure/sonic-platform-daemons/pull/62

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by daall** [comment]
retest this please

**Comment by jleveque** [comment]
Retest this please

**Pull request merged**
