### PR TITLE
route_check: Updates

### PR DESCRIPTION
**Pull request by renukamanavalan**
1) Route check skip routes that are loopback. But if those entries has valid nexthop, they are not ignored from check.

2) The vrf routes are *not* handled by route_check.

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by renukamanavalan** [comment]
retest this please

**Comment by daall** [comment]
@renukamanavalan there are merge conflicts w/ 202012, please submit a PR for the 202012 branch.

**Comment by renukamanavalan** [comment]
@daall, this conflict because, there is an update from #1363.
Requested @abdosi to know, if that could be cherry-picked for 202012.

**Comment by yxieca** [comment]
@renukamanavalan we are not taking #1363 to 202012. Please submit separate PR for this change to 202012 branch.

**Pull request merged**
