### PR TITLE
[doc][fwutil]: Update command reference: per component FW update

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

#### What I did
* Updated command reference to match `fwutil` v.2.0.0.0

#### How I did it
* Updated command reference

#### How to verify it
* N/A

#### Previous command output (if the output of a command-line utility has changed)
* N/A

#### New command output (if the output of a command-line utility has changed)
* N/A

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by nazariig** [comment]
@yxieca / @prsunny please help to merge

**Comment by nazariig** [comment]
@prsunny can you please help to merge?

**Comment by prsunny** [comment]
> @prsunny can you please help to merge?

Prefer to have @sujinmkang signoff and merge

**Comment by nazariig** [comment]
@sujinmkang please help to merge

**Comment by nazariig** [comment]
@sujinmkang please help to merge

**Review by sujinmkang — APPROVED** [review]

**Pull request merged**
