### PR TITLE
[Phase 1] Changes to the config commands for Multi-ASIC devices.

### PR DESCRIPTION
**Pull request by judyjoseph**
**- What I did**
[Phase 1] Changes to the following config commands and scripts for Multi-ASIC devices.
1. config load : supports config load across all namespaces
   > Added an optional argument to specify the namespace [ -n namesapce ]
2. config save  : supports config save across all namespaces
   > Added an optional argument to specify the namespace [ -n namesapce ]
3. config reload
   > Supports reload of all services across namespaces.
4. config interface
   > Added an optional argument to specify the namespace. [ -n namesapce ]
       In Multi-ASIC devices "Mandatory" for Portchannel and Vlan interfaces. 
                                           "Optional" for physical interface, sub interface
5. config vlan
   > Added an optional argument to specify the namespace. [ -n namesapce ]
       In Multi-ASIC devices "Mandatory" for (add/del) of vlan. 
                                          "Optional" for member interface (add/del)
6. config portchannel
   > Added an optional argument to specify the namespace. [ -n namesapce ]
       In Multi-ASIC devices "Mandatory" for (add/del) of portchannel. 
                                          "Optional" for member interface (add/del)
7. config bgp 
    > In Multi-ASIC devices, **shutdown/startup all** is performed only on external BGP neighbors.                              
                                            internal IBGP sessions between ASIC's which won't be affected. 

Additional scripts modified are 
(1) db_migrator.py
(2) portconfig

Refer **https://github.com/Azure/sonic-py-swsssdk/pull/63** for changes in SonicV2Connector and ConfigDBConnector classes.

**- How I did it**
The following are the changes introduced in this PR
(a) Added the namespace argument to the scripts db_migrator.py and portconfig

(b) Added API's to get the multi_asic mode, namesapces based on sub_role field in DEVICE_METADATA, internal host names, get the namespace to which the interface belongs ( I check the port_config.ini for finding this **Reference:** https://github.com/Azure/sonic-buildimage/tree/master/device/virtual/x86_64-kvm_x86_64-r0/msft_multi_asic_vs)

(c) added the parameter of config_db to the interface and bgp neighbor helper API's. This approach is better as the init of config_db = ConfigDBConnector() is done already in the CLI handlers where these helper API's are invoked.

(d) Updated the API _get_all_neighbor_ipaddresses() to pass an additional parameter if there are any hosts to be ignored when returning the list back.

(e) config load/save commands : If the namespace parameter is given, the action is done only for that namespace. If no argument given the action is taken on the global namespace + if we are in multi-asic platform repeat the action in the namespaces.

(f) config reload command : There is no namespace parameter added to this command. It automatically finds the namespaces present and does reload.

(g) For the config interface, config port channel, config vlan -- added the namespace parameter. It is optional by default .This parameter is made mandatory for the following 
                    - create Portchannel interfaces
                    - create vlan.
                    - config interface commands with interfaces Portchannel, vlan Interface

(h) config bgp commands : In multi-ASIC devices we have both internal BGP sessions between the bgp dockers running in different namespaces ( mapped per ASIC ). The **config shutdown/startup all** bgp neighbors command is implemented so that it affects only the external BGP neighbors

**- How to verify it**
Verified on a multi-ASIC devices, by running the Config commands. 

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by lguohan** [comment]
build failure, please fix first.

**Comment by judyjoseph** [comment]
> build failure, please fix first.

Updated Guohan, had this in my local work space , pushed the changes now.

**Comment by judyjoseph** [comment]
> build failure, please fix first.
> 
> Updated Guohan, had this in my local work space , pushed the changes now.

But on a second thought, this build will again fail .. as the code changes here in this PR will need the new infra of passing the namespace to the SonicV2Connector/ConfigDBConnector classes ( https://github.com/Azure/sonic-py-swsssdk/pull/63)

**Comment by judyjoseph** [comment]
Closing this PR as this is being split into two or more other smaller PR's

**Pull request closed without merging**
