### PR TITLE
[202012][natshow] Fix undefined variable error for fetch_translations

### LINKED ISSUE #1616: [202012]: CLI command 'show nat translation' does not work
#### Description
CLI command 'show nat translation' does not work for SONiC 202012:

`admin@dut:~$ show nat translation
name 's' is not defined`

Looks like /usr/local/bin/natshow script's method fetch_translations has undefined variable 's' on [line 137](https://github.com/Azure/sonic-utilities/blob/ab440675ed80c2ff6e996ef2cfbcbb1cf77375fa/scripts/natshow#L137) :
`ent = self.asic_db.get_all('ASIC_DB', s, blocking=True)`

#### Output of `show version`

```
SONiC Software Version: SONiC.202012.13017-dirty-20210429.085631                            
Distribution: Debian 10.9                                                                   
Kernel: 4.19.0-12-2-amd64                                                                   
Build commit: 04723238
Build date: Thu Apr 29 14:32:34 UTC 2021     
Built by: AzDevOps@sonic-build-workers-0007WT
              
Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C
ASIC: barefoot
ASIC Count: 1
Uptime: 10:59:45 up 2 min,  1 user,  load average: 2.10, 1.09, 0.43
Docker images:
REPOSITORY                    TAG                                  IMAGE ID            SIZE
docker-syncd-bfn              202012.13017-dirty-20210429.085631   3d7187773f80        1.2GB
docker-syncd-bfn              latest                               3d7187773f80        1.2GB
docker-teamd                  202012.13017-dirty-20210429.085631   3392c52e17a5        410MB
docker-teamd                  latest                               3392c52e17a5        410MB
docker-nat                    202012.13017-dirty-20210429.085631   41ce3b6cc504        413MB
docker-nat                    latest                               41ce3b6cc504        413MB
docker-platform-monitor       202012.13017-dirty-20210429.085631   f6f7f55d9800        608MB
docker-platform-monitor       latest                               f6f7f55d9800        608MB
docker-lldp                   202012.13017-dirty-20210429.085631   512aae27db3e        440MB
docker-lldp                   latest                               512aae27db3e        440MB
docker-snmp                   202012.13017-dirty-20210429.085631   f58891dcbd93        441MB
docker-snmp                   latest                               f58891dcbd93        441MB
docker-dhcp-relay             202012.13017-dirty-20210429.085631   c89f5f1573e1        407MB
docker-dhcp-relay             latest                               c89f5f1573e1        407MB
docker-database               202012.13017-dirty-20210429.085631   b30f2370340a        400MB
docker-database               latest                               b30f2370340a        400MB
docker-router-advertiser      202012.13017-dirty-20210429.085631   eebdcbc196c8        400MB
docker-router-advertiser      latest                               eebdcbc196c8        400MB
docker-orchagent              202012.13017-dirty-20210429.085631   fe99d3937ac2        429MB
docker-orchagent              latest                               fe99d3937ac2        429MB
docker-sonic-telemetry        202012.13017-dirty-20210429.085631   e52705751026        489MB
docker-sonic-telemetry        latest                               e52705751026        489MB
docker-sonic-mgmt-framework   202012.13017-dirty-20210429.085631   0d43b6fa8251        618MB
docker-sonic-mgmt-framework   latest                               0d43b6fa8251        618MB
docker-fpm-frr                202012.13017-dirty-20210429.085631   b956a1d081d7        428MB
docker-fpm-frr                latest                               b956a1d081d7        428MB
docker-sflow                  202012.13017-dirty-20210429.085631   3a09f2d6b487        411MB
docker-sflow                  latest                               3a09f2d6b487        411MB

```

### PR DESCRIPTION
**Pull request by monipko**
Fixed undefined variable error for fetch_translation method, closes #1616 
<!--
    Please make sure you've read and understood our contributing guidelines:
    https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

    ** Make sure all your commits include a signature generated with `git commit -s` **

    If this is a bug fix, make sure your description includes "closes #xxxx",
    "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
    issue when the PR is merged.

    If you are adding/modifying/removing any command or utility script, please also
    make sure to add/modify/remove any unit tests from the tests
    directory as appropriate.

    If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
    subcommand, or you are adding a new subcommand, please make sure you also
    update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
    your changes.

    Please provide the following information:
-->


#### Previous command output (if the output of a command-line utility has changed)
```
admin@dut:~$ show nat translation                                                                                           
name 's' is not defined 
```

#### New command output (if the output of a command-line utility has changed)
```
admin@dut:~$ show nat translation                                                                                           
                                                                                                                                    
Static NAT Entries         ..................... 0                                                                                  
Static NAPT Entries        ..................... 0                                                                                  
Dynamic NAT Entries        ..................... 0                                                                                  
Dynamic NAPT Entries       ..................... 0                                                                                  
Static Twice NAT Entries   ..................... 0                                                                                  
Static Twice NAPT Entries  ..................... 0                                                                                  
Dynamic Twice NAT Entries  ..................... 0                                                                                  
Dynamic Twice NAPT Entries ..................... 0                                                                                  
Total SNAT/SNAPT Entries   ..................... 0                                                                                  
Total DNAT/DNAPT Entries   ..................... 0                                                                                            
Total Entries              ..................... 0                                                                                                                   
                                                                                                                                                  
Protocol    Source    Destination    Translated Source    Translated Destination                                                                  
----------  --------  -------------  -------------------  ------------------------ 
```

### CODE REVIEW

**Comment by AkhileshSamineni** [comment]
Code changes looks Okay. Please merge this one.

**Comment by monipko** [comment]
@yxieca, @abdosi could you please merge

**Comment by yxieca** [comment]
@monipko can you elaborate why this change is not needed in master branch? Was there a cherry-pick error caused this issue?

**Comment by AkhileshSamineni** [comment]
> @monipko can you elaborate why this change is not needed in master branch? Was there a cherry-pick error caused this issue?

@yxieca This change is present in master branch (PR - https://github.com/Azure/sonic-utilities/pull/1383).

**Review by yxieca — APPROVED** [review]

**Comment by anshuv-mfst** [comment]
Is the issue fixed for master branch as well?

**Pull request merged**
