### PR TITLE
[config]: Add config acl add/remove table command

### PR DESCRIPTION
**Pull request by stcheng**
Add below two commands:
config acl add table <table_name> <table_type>
config acl remove table <table_name>

note:
add table supports description and ports

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

### CODE REVIEW

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by kannankvs** [comment]
@jleveque, @stcheng  : Looks like the CLI document is not updated for this command.

**Comment by jleveque** [comment]
@stcheng: Can you please update the CLI document to reflect these changes?

**Pull request merged**
