### PR TITLE
Modified the 'show ipv6 link-local-mode' command to display all interfaces by default

### PR DESCRIPTION
**Pull request by AkhileshSamineni**
Modified the 'show ipv6 link-local-mode' command to display all interfaces by default

#### What I did
The current show command will display the link-local mode only when RIF is present for the interface.
As Issue https://github.com/Azure/sonic-buildimage/issues/8610 asks to display the link-local-mode for all interfaces.
```
root@sonic:/home/admin# show ipv6 link-local-mode 
+------------------+--------+
| Interface Name   | Mode   |
+==================+========+
+------------------+--------+
root@sonic:/home/admin# 
root@sonic:/home/admin# config interface ipv6 enable use-link-local-only Ethernet48 
root@sonic:/home/admin# 
root@sonic:/home/admin# 
root@sonic:/home/admin# show ipv6 link-local-mode 
+------------------+---------+
| Interface Name   | Mode    |
+==================+=========+
| Ethernet48       | Enabled |
+------------------+---------+
root@sonic:/home/admin# 
root@sonic:/home/admin# 
```
#### How I did it
Added code changes to display all the link-local-mode for all the interfaces (Port, Portchannel and Vlan).

#### How to verify it
```
root@sonic:/home/admin# config portchannel add PortChannel10
root@sonic:/home/admin# config portchannel add PortChannel20
root@sonic:/home/admin# config vlan add 10
root@sonic:/home/admin# config vlan add 20
root@sonic:/home/admin# config interface ipv6 enable use-link-local-only Ethernet9
root@sonic:/home/admin# config interface ipv6 enable use-link-local-only PortChannel10
root@sonic:/home/admin# config interface ipv6 enable use-link-local-only Vlan10
root@sonic:/home/admin# show ipv6 link-local-mode 
+------------------+----------+
| Interface Name   | Mode     |
+==================+==========+
| Ethernet0        | Disabled |
+------------------+----------+
| Ethernet1        | Disabled |
+------------------+----------+
| Ethernet10       | Disabled |
+------------------+----------+
| Ethernet11       | Disabled |
+------------------+----------+
| Ethernet12       | Disabled |
+------------------+----------+
| Ethernet13       | Disabled |
+------------------+----------+
| Ethernet14       | Disabled |
+------------------+----------+
| Ethernet15       | Disabled |
+------------------+----------+
| Ethernet16       | Disabled |
+------------------+----------+
| Ethernet17       | Disabled |
+------------------+----------+
| Ethernet18       | Disabled |
+------------------+----------+
| Ethernet19       | Disabled |
+------------------+----------+
| Ethernet2        | Disabled |
+------------------+----------+
| Ethernet20       | Disabled |
+------------------+----------+
| Ethernet21       | Disabled |
+------------------+----------+
| Ethernet22       | Disabled |
+------------------+----------+
| Ethernet23       | Disabled |
+------------------+----------+
| Ethernet24       | Disabled |
+------------------+----------+
| Ethernet25       | Disabled |
+------------------+----------+
| Ethernet26       | Disabled |
+------------------+----------+
| Ethernet27       | Disabled |
+------------------+----------+
| Ethernet28       | Disabled |
+------------------+----------+
| Ethernet29       | Disabled |
+------------------+----------+
| Ethernet3        | Disabled |
+------------------+----------+
| Ethernet30       | Disabled |
+------------------+----------+
| Ethernet31       | Disabled |
+------------------+----------+
| Ethernet32       | Disabled |
+------------------+----------+
| Ethernet33       | Disabled |
+------------------+----------+
| Ethernet34       | Disabled |
+------------------+----------+
| Ethernet35       | Disabled |
+------------------+----------+
| Ethernet36       | Disabled |
+------------------+----------+
| Ethernet37       | Disabled |
+------------------+----------+
| Ethernet38       | Disabled |
+------------------+----------+
| Ethernet39       | Disabled |
+------------------+----------+
| Ethernet4        | Disabled |
+------------------+----------+
| Ethernet40       | Disabled |
+------------------+----------+
| Ethernet41       | Disabled |
+------------------+----------+
| Ethernet42       | Disabled |
+------------------+----------+
| Ethernet43       | Disabled |
+------------------+----------+
| Ethernet44       | Disabled |
+------------------+----------+
| Ethernet45       | Disabled |
+------------------+----------+
| Ethernet46       | Disabled |
+------------------+----------+
| Ethernet47       | Disabled |
+------------------+----------+
| Ethernet48       | Disabled |
+------------------+----------+
| Ethernet49       | Disabled |
+------------------+----------+
| Ethernet5        | Disabled |
+------------------+----------+
| Ethernet50       | Disabled |
+------------------+----------+
| Ethernet51       | Disabled |
+------------------+----------+
| Ethernet52       | Disabled |
+------------------+----------+
| Ethernet53       | Disabled |
+------------------+----------+
| Ethernet54       | Disabled |
+------------------+----------+
| Ethernet55       | Disabled |
+------------------+----------+
| Ethernet56       | Disabled |
+------------------+----------+
| Ethernet57       | Disabled |
+------------------+----------+
| Ethernet58       | Disabled |
+------------------+----------+
| Ethernet59       | Disabled |
+------------------+----------+
| Ethernet6        | Disabled |
+------------------+----------+
| Ethernet60       | Disabled |
+------------------+----------+
| Ethernet61       | Disabled |
+------------------+----------+
| Ethernet62       | Disabled |
+------------------+----------+
| Ethernet63       | Disabled |
+------------------+----------+
| Ethernet64       | Disabled |
+------------------+----------+
| Ethernet65       | Disabled |
+------------------+----------+
| Ethernet66       | Disabled |
+------------------+----------+
| Ethernet67       | Disabled |
+------------------+----------+
| Ethernet68       | Disabled |
+------------------+----------+
| Ethernet69       | Disabled |
+------------------+----------+
| Ethernet7        | Disabled |
+------------------+----------+
| Ethernet70       | Disabled |
+------------------+----------+
| Ethernet71       | Disabled |
+------------------+----------+
| Ethernet8        | Disabled |
+------------------+----------+
| Ethernet9        | Enabled  |
+------------------+----------+
| PortChannel10    | Enabled  |
+------------------+----------+
| PortChannel20    | Disabled |
+------------------+----------+
| Vlan10           | Enabled  |
+------------------+----------+
| Vlan20           | Disabled |
+------------------+----------+
root@sonic:/home/admin# 
```
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

### CODE REVIEW

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
@prsunny Please review the changes.

**Comment by prsunny** [comment]
@dgsudharsan , could you please review/signoff?

**Review by dgsudharsan — APPROVED** [review]

**Comment by dgsudharsan** [comment]
Required for 202106

**Review by prsunny — APPROVED** [review]

**Comment by dgsudharsan** [comment]
Request for 202106

**Pull request merged**
