### PR TITLE
[tests]: mv feature_test into tests folder

### PR DESCRIPTION
**Pull request by lguohan**
Signed-off-by: Guohan Lu <lguohan@gmail.com>

**- What I did**
mv feature_test.py into tests folder

**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by lguohan** [comment]
@jleveque, looks like build is broken, can you check why?

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
> @jleveque, looks like build is broken, can you check why?

@lguohan: This PR should fix the build: https://github.com/Azure/sonic-build-tools/pull/143

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Pull request merged**
