### PR TITLE
[show] add 'show ip interfaces' command

### PR DESCRIPTION
**Pull request by tsvanduyn**
**- What I did**
add a command "show ip interfaces"
This gets the IP address, int status, optics, MTU, and LLDP neighbors and aggregates them into one command. 

**- How I did it**
Ran these 4x commands
show int summary
show int status
show int transceiver eeprom 
show lldp table 

Used textfsm to parse the commands into dictionaries with the interface as the key.
Then combined the 4x dictionaries into one dictionary and printed the output.

**- How to verify it**
show ip interfaces 

**- Previous command output (if the output of a command-line utility has changed)**
None 

**- New command output (if the output of a command-line utility has changed)**
root@str-s6000-acs-11:/usr/lib/python2.7/dist-packages/show# show ip interfaces 
Interface    IPv4Address      MTU    Speed    Oper    Admin    OpticPresent    OpticType    OpticModel    Neighbor          NeighborPort
-----------  ---------------  -----  -------  ------  -------  --------------  -----------  ------------  ----------------  --------------
Ethernet0    10.0.0.0/31      9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet4    10.0.0.2/31      9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet8    10.0.0.4/31      9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet12   10.0.0.6/31      9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet16   10.0.0.8/31      9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet20   10.0.0.10/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet24   10.0.0.12/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet28   10.0.0.14/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet32   10.0.0.16/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet36   10.0.0.18/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet40   10.0.0.20/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet44   10.0.0.22/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet48   10.0.0.24/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet52   10.0.0.26/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet56   10.0.0.28/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet60   10.0.0.30/31     9100   40G      up      down     not detected
Ethernet64   10.0.0.32/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet68   10.0.0.34/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet72   10.0.0.36/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet76   10.0.0.38/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet80   10.0.0.40/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet84   10.0.0.42/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet88   10.0.0.44/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet92   10.0.0.46/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet96   10.0.0.48/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet100  10.0.0.50/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet104  10.0.0.52/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet108  10.0.0.54/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet112  10.0.0.56/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet116  10.0.0.58/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet120  10.0.0.60/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
Ethernet124  10.0.0.62/31     9100   40G      up      up       detected        QSFP+        40GBASE-CR4
eth0         10.3.147.239/23                                                                              str-22ex-235ab08  ge-0/0/29
lo           127.0.0.1/8
-->

### CODE REVIEW

**Comment by prsunny** [comment]
What if there are two IP addresses for an interface. Can you provide a sample output?

**Comment by tsvanduyn** [comment]
Nikos
When I started to work on this I didn't realize you were still working on this since you originally checked in your changes last November.   Do you have an ETA on when you are going to update the comments and get your code checked in? 
Can you tell me why the requirements for the kernel interfaces are necessary?  I'm assuming you mean the docker, eth0, and bridge interfaces. 

Also the reason I added the nbrs, optics, etc into one is command is this is what I would like to see when I ran a command instead of having to run multiple commands to get this output.   Is there a reason you would rather run multiple commands instead of having it in one command?   Since this project is something that can be updated by the community then I don't think we should have to stick 1:1 with how Cisco/Arista did it.  
I do agree that the optics info should be added to the "show int status" command but I don't see the harm in having it in the output of "show ip interface".

**Comment by tsvanduyn** [comment]
Prsunny,
I didn't have a test box with 2 IPv4 addresses on an interface.  I'll have to test and add that.   Good question. :)

**Comment by nikos-github** [comment]
@tsvanduyn I will address the comments this week and repost. Our requirement is for all interfaces not just the front panel ports or only the set of ephemeral interfaces sonic support. I have no problem with the output you added but if you try with ipv6 addresses, the output will be cumbersome and unreadable. If you still think you want that info hanging off a command that is meant to show addresses, then a reasonable compromise would be to provide a detail keyword. I don't believe a command's output should be a kitchen sink for every possible information about an object.

**Comment by tsvanduyn** [comment]
Nikos,

Sorry for the late response.  I've submitted this PR to add the optics info on the "show interface status" command:
https://github.com/Azure/sonic-utilities/pull/407

I'll wait for you command to get checked before I look at that again for the next steps. 
Are you still ontrack to submit this in week?

**Comment by nikos-github** [comment]
@tsvanduyn I addressed the comments for my PR. It just needs to be merged now.

**Comment by tsvanduyn** [comment]
Sounds good.  I'll wait for your command to get merged.  Thanks!

**Comment by jleveque** [comment]
Closing in favor of https://github.com/Azure/sonic-utilities/pull/194.

**Pull request closed without merging**
