### PR TITLE
[show]: add transceiver info 

### PR DESCRIPTION
**Pull request by mudsut4ke**
**- What I did**
- Add transceiver info display to show command

**- How I did it**
- Implement `transceivershow` script
- Add transceivershow to show command

**- How to verify it**
- Run command `show interfaces transceiver info `
- [transceiver_info_test.log](https://github.com/Azure/sonic-utilities/files/4791798/transceiver_info_test.log)

**- Previous command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ show interfaces transceiver 
Usage: show interfaces transceiver [OPTIONS] COMMAND [ARGS]...

  Show SFP Transceiver information

Options:
  -?, -h, --help  Show this message and exit.

Commands:
  eeprom    Show interface transceiver EEPROM information
  lpmode    Show interface transceiver low-power mode status
  presence  Show interface transceiver presence
```
**- New command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ show interfaces transceiver 
Usage: show interfaces transceiver [OPTIONS] COMMAND [ARGS]...

  Show SFP Transceiver information

Options:
  -?, -h, --help  Show this message and exit.

Commands:
  eeprom    Show interface transceiver EEPROM information
  info      Show interface transceiver information
  lpmode    Show interface transceiver low-power mode...
  presence  Show interface transceiver presence

admin@sonic:~$ show interfaces transceiver info Ethernet0
Interface    Type               Number of lanes  Vendor Name    Model Name          Serial Number    Nominal bit rate[100Mbs]
-----------  ---------------  -----------------  -------------  ----------------  ---------------  --------------------------
Ethernet0    QSFP28 or later                  4  ColorChip ltd  C100QSFPCWDM400B         18130506                         255

admin@sonic:~$ show interfaces transceiver info --dom Ethernet0
Interface    Lane Number    Temp[C]                         Voltage[V]                       Current[mA]                    Tx Power[dBm]                    Rx Power[dBm]
-----------  -------------  ------------------------------  -------------------------------  -----------------------------  -------------------------------  --------------------------------
Ethernet0    Lane 1         37.371 [low=0.000, high=75.000]  3.276 [low=3.134, high=3.465]  44.954 [low=28.392, high=49.000]  -1.018 [low=-9.5001, high=2.400]  -1.018 [low=-9.5001, high=2.400]
             Lane 2         37.371 [low=0.000, high=75.000]  3.276 [low=3.134, high=3.465]  38.386 [low=28.392, high=49.000]  -1.385 [low=-9.5001, high=2.400]  -1.385 [low=-9.5001, high=2.400]
             Lane 3         37.371 [low=0.000, high=75.000]  3.276 [low=3.134, high=3.465]  35.166 [low=28.392, high=49.000]  -0.391 [low=-9.5001, high=2.400]  -0.391 [low=-9.5001, high=2.400]
             Lane 4         37.371 [low=0.000, high=75.000]  3.276 [low=3.134, high=3.465]  36.156 [low=28.392, high=49.000]  -1.720 [low=-9.5001, high=2.400]  -1.720 [low=-9.5001, high=2.400]
```

**Signed-off-by**: Wirut Getbamrung [wgetbumr@celestica.com]

### CODE REVIEW

**Comment by jleveque** [comment]
Thanks for this PR! I'd also like to be able to display the threshold values along with the DOM info. I'm not sure if we should show them by default, or if we should use your current output by default and add an extra flag which will expand the output to include the threshold values.

Also, can you please add the new `show interfaces transceiver info` command to doc/Command-Reference.md?

**Comment by mudsut4ke** [comment]
@jleveque , Thank you for your comment 
I will try to add the threshold values along with the DOM info and add this command to doc/Command-Reference.md

**Comment by jleveque** [comment]
@mudsut4ke: There is already an exiting 'sfpshow' utility, sonic-utilities/scripts/sfpshow. Thus it appears to be redundant to have a second utility for similar purposes. Can you please look into merging the two into one?

**Comment by mudsut4ke** [comment]
> @mudsut4ke: There is already an exiting 'sfpshow' utility, sonic-utilities/scripts/sfpshow. Thus it appears to be redundant to have a second utility for similar purposes. Can you please look into merging the two into one?

@jleveque , I try to merge it on https://github.com/Azure/sonic-utilities/pull/1030, please help review it again

**Pull request closed without merging**
