### PR TITLE
[Mellanox] add document for thermal control related cli

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- What I did**

1. Add command description for show platform fan
2. Add command description for show platform temperature

**- How I did it**

**- How to verify it**

Verify it by preview the markdown document.

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
Hi @liat-grozovik , I discussed with @keboliu about provide a high level description about thermal policy management. And we agreed to add that section in thermal control design document. You can see it here https://github.com/Junchao-Mellanox/SONiC/pull/2. What's your suggestion?

**Comment by Junchao-Mellanox** [comment]
retest default please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by daall** [comment]
retest this please

**Pull request merged**
