### PR TITLE
[aclshow] output only counters per table/rule

### PR DESCRIPTION
**Pull request by romankachur-mlnx**
**- What I did**
Modified _aclshow_ utility.

1. Removed three unneeded columns (Type / Priority / Action) from the output 
(as this information is duplicated by _acl-loader_ utility).
2. Removed unneeded arguments (_details_ and _ports_) passed to the utility.
3. Added handling of arguments (_rules_ and _tables_), which were accepted by the utility but not handled 
(now the output is filtered based on the passed arguments).

**- How I did it**
Modified _scripts/aclshow_
**- How to verify it**
Run _aclshow_ utility with all possible options:
_aclshow_
_aclshow -h_
_aclshow -a -vv_
_aclshow -t <existing_table,unexisting_table> -a_
_aclshow -r <existing_rule,unexisting_rule> -a_
**- Previous command output (if the output of a command-line utility has changed)**
```
aclshow   -a -t DATAACL -r RULE_2,RULE_3,DEFAULT_RULE -vv
Reading ACL info...
ACL Tables to show: 4
ACL Rules to show: 14
ACL Counters found: 14

RULE NAME     TABLE NAME    TYPE      PRIO  ACTION      PACKETS COUNT    BYTES COUNT
------------  ------------  ------  ------  --------  ---------------  -------------
RULE_1        DATAACL       L3        9999  FORWARD                 0              0
RULE_2        DATAACL       L3        9998  FORWARD                 0              0
RULE_3        DATAACL       L3        9997  FORWARD                 0              0
RULE_4        DATAACL       L3        9996  FORWARD                 0              0
RULE_5        DATAACL       L3        9995  FORWARD                 0              0
RULE_6        DATAACL       L3        9994  FORWARD                 0              0
RULE_7        DATAACL       L3        9993  DROP                    0              0
RULE_8        DATAACL       L3        9992  FORWARD                 0              0
RULE_9        DATAACL       L3        9991  FORWARD                 0              0
RULE_10       DATAACL       L3        9990  FORWARD                 0              0
RULE_11       DATAACL       L3        9989  FORWARD                 0              0
RULE_12       DATAACL       L3        9988  FORWARD                 0              0
RULE_13       DATAACL       L3        9987  FORWARD                 0              0
DEFAULT_RULE  DATAACL       L3           1  DROP                 5157         402246

```

**- New command output (if the output of a command-line utility has changed)**
```
aclshow   -a -t DATAACL -r RULE_2,RULE_3,DEFAULT_RULE -vv
Reading ACL info...
Total number of ACL Tables: 4
Total number of ACL Rules: 14

RULE NAME     TABLE NAME      PACKETS COUNT    BYTES COUNT
------------  ------------  ---------------  -------------
DEFAULT_RULE  DATAACL                  5177         403806
RULE_2        DATAACL                     0              0
RULE_3        DATAACL                     0              0

```
-->

### CODE REVIEW

**Comment by andriymoroz-mlnx** [comment]
retest this please

**Comment by romankachur-mlnx** [comment]
retest this please

**Comment by liat-grozovik** [comment]
@romankachur-mlnx please fix commit typo 'acs- to acl-'
The output of the new aclshow only provides counters' information per table/per rule. The info about the rule/table should be retrieved from 'acl-loader show'.
@lguohan now that the aclshow only handles ACL counters should we change the name? 

@romankachur-mlnx it might be a good idea to send in the mailing list that the UI is going to change. we dont know if SONiC users has any automation based on it which is not exposed and the community need some time to get ready for it.

**Comment by romankachur-mlnx** [comment]
retest this please

**Comment by liat-grozovik** [comment]
> > now that the aclshow only handles ACL counters should we change the name?
> 
> Maybe we should consider combining acl-loader and aclshow logic into one utility, "aclutil"?

Following offline discussion it was agreed to have this fix regardless on the suggestion raised.
The idea is to have an existing tool working (fixes few detected issues) and then work on new UI for ACL show and config. From my understanding such UI will be defined as part of the everflow improvements.

**Pull request merged**
