### PR TITLE
[fast-reboot] Remove FLEX_COUNTER_TABLE from config_db.json before reboot

### PR DESCRIPTION
**Pull request by vaibhavhd**
#### What I did

This is porting changes from 202012 branch to 201911 branch.
Related PR: https://github.com/Azure/sonic-utilities/pull/1774

### CODE REVIEW

**Comment by prsunny** [comment]
@vaibhavhd, could you please ensure this is required for 201911. As the branch is pretty much stable, suggest to cherry-pick only if absolutely required.

**Comment by vaibhavhd** [comment]
> @vaibhavhd, could you please ensure this is required for 201911. As the branch is pretty much stable, suggest to cherry-pick only if absolutely required.

The need was highlighted by @shlomibitton, where Mellanox found out that fastboot dataplane downtime has increased since the tables are present and enabled after fast-reboot.

**Comment by vaibhavhd** [comment]
I will run a test to see how much dataplane downtime improvement this PR brings in 201911 branch.

**Review by yxieca — APPROVED** [review]

**Comment by yxieca** [comment]
@prsunny this change is needed when warm reboot upgrade from 201911 to 202012 and above images.

**Pull request merged**
