### PR TITLE
Fix sFlow show CLI cosmetics

### PR DESCRIPTION
**Pull request by GarrickHe**
**- What I did**
Fix a minor cosmetic issue for the sFlow show command where collector information was not aligned

**- How I did it**
Increase the ljust width

**- How to verify it**
Ran the 'show sflow' command and

**- Previous command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          enable
  sFlow Polling Interval:     4444444444
  sFlow AgentID:              default

  2 Collectors configured:
    Name: abcdefg             IP addr: 100.100.100.100UDP port: 65535
    Name: col12345679ABCDE    IP addr: 100.101.111.254UDP port: 23456
```

**- New command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          enable
  sFlow Polling Interval:     4444444444
  sFlow AgentID:              default

  2 Collectors configured:
    Name: abcdefg             IP addr: 100.100.100.100    UDP port: 65535
    Name: col12345679ABCDE    IP addr: 100.101.111.254    UDP port: 23456
```

### CODE REVIEW

**Comment by prsunny** [comment]
can you please rebase to master, it shows previous diffs

**Comment by GarrickHe** [comment]
> can you please rebase to master, it shows previous diffs

Done.

**Comment by jleveque** [comment]
Retest this please

**Comment by GarrickHe** [comment]
Will need to reopen this.

**Comment by GarrickHe** [comment]
@prsunny - I accidentally closed this. I'll re-open when the other sFlow CLI change is merged.

**Pull request closed without merging**
