### PR TITLE
[sonic-utilities] fix config/show vlan members

### PR DESCRIPTION
**Pull request by dawnbeauty**
**- What I did**
fixes Azure/SONiC issue [323](https://github.com/Azure/SONiC/issues/323)

**- How I did it**
As the issue mentioned, the "members@" field of VLAN is for backward compatibility.
Utility script should no longer use it when config add/del vlan members.

- config add vlan members
pre-add: check "members" of given vlan entry and vlan members table to ensure that the interface is not a member of given vlan.
add: add interface to VLAN_MEMBER table. (not to "members" of vlan.)

- config del vlan members
pre-del: check "members" of given vlan entry and vlan members table to ensure that the interface is a member of given vlan.
del: not only remove interface from VLAN_MEMBER table but also from "members" of vlan(if existing)

- show vlan config
collect members info from "members" list of given vlan and VLAN_MEMBER_TABLE.

**- How to verify it**
assume boot with below vlan configuration in config_db.json
```
    "VLAN": {
        "Vlan100": {
            "vlanid": "100"
        },
        "Vlan200": {
            "vlanid": "200"
        }
    },
    "VLAN_MEMBER": {
        "Vlan100|Ethernet0": {
            "tagging_mode": "untagged"
        },
        "Vlan100|Ethernet1": {
            "tagging_mode": "untagged"
        },
        "Vlan200|Ethernet2": {
            "tagging_mode": "tagged"
        },
        "Vlan200|Ethernet3": {
            "tagging_mode": "tagged"
        }
    }
```
**- Previous command output (if the output of a command-line utility has changed)**
- show
```
admin@sonic:~$ show vlan brief
+-----------+-------------------+-----------+----------------+-----------------------+
|   VLAN ID | IP Address        | Ports     | Port Tagging   | DHCP Helper Address   |
+===========+===================+===========+================+=======================+
|       100 | 10.1.1.1/24       | Ethernet0 | untagged       |                       |
|           | 2000::10:1:1:1/80 | Ethernet1 | untagged       |                       |
+-----------+-------------------+-----------+----------------+-----------------------+
|       200 | 20.1.1.1/24       | Ethernet2 | tagged         |                       |
|           | 2000::20:1:1:1/80 | Ethernet3 | tagged         |                       |
+-----------+-------------------+-----------+----------------+-----------------------+
admin@sonic:~$ show vlan config
Name       VID
-------  -----
Vlan100    100
Vlan200    200
```
**NOTICE**: here we could not get vlan member output from `show vlan config`

- config del vlan member
```
admin@sonic:~$ sudo config vlan member del 100 Ethernet0
Usage: config vlan member del [OPTIONS] <vid> <interface_name>

Error: Ethernet0 is not a member of Vlan100
```
- config add vlan member
```
sudo config vlan member add 100 Ethernet4
admin@sonic:~$ redis-cli -n 4 hgetall "VLAN|Vlan100" 
1) "vlanid"
2) "100"
3) "members@"
4) "Ethernet4"

admin@sonic:~$ show vlan config
Name       VID  Member     Mode
-------  -----  ---------  ------
Vlan100    100  Ethernet4  tagged
Vlan200    200
```

**- New command output (if the output of a command-line utility has changed)**
- show
```
admin@sonic:~$ show vlan config
Name       VID  Member     Mode
-------  -----  ---------  --------
Vlan100    100  Ethernet0  untagged
Vlan100    100  Ethernet1  untagged
Vlan200    200  Ethernet2  tagged
Vlan200    200  Ethernet3  tagged
```
- config del vlan member
```
admin@sonic:~$ sudo config vlan member del 100 Ethernet0
admin@sonic:~$ show vlan config
Name       VID  Member     Mode
-------  -----  ---------  --------
Vlan100    100  Ethernet1  untagged
Vlan200    200  Ethernet2  tagged
Vlan200    200  Ethernet3  tagged
```
- config add vlan member
```
admin@sonic:~$ sudo config vlan member add 100 Ethernet4
admin@sonic:~$ redis-cli -n 4 hgetall "VLAN|Vlan100"                
1) "vlanid"
2) "100"
admin@sonic:~$ show vlan config
Name       VID  Member     Mode
-------  -----  ---------  --------
Vlan100    100  Ethernet1  untagged
Vlan100    100  Ethernet4  tagged
Vlan200    200  Ethernet2  tagged
Vlan200    200  Ethernet3  tagged
```

### CODE REVIEW

**Comment by prsunny** [comment]
Can you update the description with previous and new output?

**Comment by jleveque** [comment]
@dawnbeauty: Can you update the description with previous and new output?

**Comment by dawnbeauty** [comment]
@prsunny @jleveque  Updated comments. Please review again, thanks.

**Comment by jleveque** [comment]
@dawnbeauty: Thanks. Can you also fix the recent merge conflict?

**Comment by dawnbeauty** [comment]
Done.

**Comment by jleveque** [comment]
Retest this please

**Comment by lguohan** [comment]
obsoleted by #1050

**Comment by dawnbeauty** [comment]
@lguohan #1050 only fix the show commands, how about the add/del actions?

**Pull request closed without merging**
