### PR TITLE
[show priority-group drop counters] Add user info output when user want to check PG counters and polling are disabled

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>

#### What I did
Added additional output info for user when trying to show priority group counters and pg drop counters are disabled

#### How I did it
modify pg-drop script, add additional print during executing "show priority-group drop counters" if PG polling disabled

#### How to verify it
```
counterpoll pg-drop disable
show priority-group drop counters
```
Expect:
`Warning: PG counters are disabled. Current stats may be outdated. Use 'counterpoll pg-drop enable' to enable'`

#### Previous command output (if the output of a command-line utility has changed)
```
admin@r-tigon-04:/usr/local/bin$ show priority-group drop counters
Ingress PG dropped packets:
       Port    PG0    PG1    PG2    PG3    PG4    PG5    PG6    PG7
-----------  -----  -----  -----  -----  -----  -----  -----  -----
  Ethernet0      0      0      0      0      0      0      0      0
  Ethernet2      0      0      0      0      0      0      0      0
  Ethernet8      0      0      0      0      0      0      0      0
 Ethernet10      0      0      0      0      0      0      0      0
 Ethernet16      0      0      0      0      0      0      0      0
```
#### New command output (if the output of a command-line utility has changed)
```
admin@r-tigon-04:/usr/local/bin$ show priority-group drop counters
Warning: PG counters are disabled. Use 'counterpoll pg-drop enable' to enable polling
```

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@neethajohn would like to consult with you on the suggested change. it is a good and informative but should we consider not to show the table in that case and just the note instead? what is the purpose of showing some values when the counter is disabled? in many cases it will not be 0 if was enabled and then disabled so the main question why we need it.

**Comment by liat-grozovik** [comment]
@neethajohn kindly reminder, appreciate your feedback on the above question

**Comment by neethajohn** [comment]
> @neethajohn would like to consult with you on the suggested change. it is a good and informative but should we consider not to show the table in that case and just the note instead? what is the purpose of showing some values when the counter is disabled? in many cases it will not be 0 if was enabled and then disabled so the main question why we need it.

I agree with you that showing the table makes no sense when its disabled. Looks like in the current change, we still show the counters along with the warning message.  I am fine either way - leaving it there or removing it as long as the warning is there.

**Review by neethajohn — DISMISSED** [review]

**Review by liat-grozovik — CHANGES_REQUESTED** [review]
i suggest to remove the table when it is disabled.

**Comment by ayurkiv-nvda** [comment]
> i suggest to remove the table when it is disabled.

Accepted.
Fix is really easy but creating additional unit test still in progress - faced with some difficulties.
I will add fix and appropriate UT soon

**Comment by ayurkiv-nvda** [comment]
> i suggest to remove the table when it is disabled.

Done
UT aslo added

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@neethajohn kindly reminder to review and approve. this issue is relevant for active release branches.

**Review by neethajohn — APPROVED** [review]
Please update the 'output' in the PR description to reflect this new change of not displaying counters

**Comment by ayurkiv-nvda** [comment]
> Please update the 'output' in the PR description to reflect this new change of not displaying counters

Done

**Pull request merged**
