### PR TITLE
Handling error scenario of adding port to Vlan which is part of LAG

### PR DESCRIPTION
**Pull request by dgsudharsan**
#### What I did
Handled error scenario when adding a port to Vlan which is already part of a LAG. Added unit test to cover the scenario. This is fix for the bug https://github.com/Azure/sonic-buildimage/issues/4456

#### How I did it
Fixed the config vlan script to check if port is a port channel member before setting config_db

#### How to verify it
config vlan add 10
config portchannel add PortChannel0
config portchannel member add PortChannel0 Ethernet0
config vlan member add 10 Ethernet0

Usage: config vlan member add [OPTIONS] port
Try "config vlan member add -h" for help.

Error: Ethernet0 is part of portchannel!

### CODE REVIEW

**Comment by dgsudharsan** [comment]
Please backport it to 202012 and other required releases.

**Comment by dgsudharsan** [comment]
retest vs please

**Comment by dgsudharsan** [comment]
retest this please

**Comment by dgsudharsan** [comment]
retest this please

**Review by prsunny — APPROVED** [review]

**Pull request merged**
