### PR TITLE
[show] Add missing import to fix `show ip interfaces`

### PR DESCRIPTION
**Pull request by lolyu**
Add the missing import of `netaddr` for `show ip interfaces`.

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**
```
$ show ip interfaces
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 727, in interfaces
    netmask = netaddr.IPAddress(ipaddr['netmask']).netmask_bits()
NameError: global name 'netaddr' is not defined
```
**- New command output (if the output of a command-line utility has changed)**
```
$ show ip interfaces
Interface    Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
-----------  --------  -------------------  ------------  --------------  -------------
Ethernet0              192.168.1.2/24       up/down       N/A             N/A
Ethernet28             192.168.4.1/24       up/up         N/A             N/A
docker0                240.127.1.1/24       up/down       N/A             N/A
eth0                   10.3.146.241/23      up/up         N/A             N/A
lo                     127.0.0.1/16         up/up         N/A             N/A
```

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by neethajohn** [comment]
same as #1129

**Comment by jleveque** [comment]
@neethajohn: I just closed https://github.com/Azure/sonic-utilities/pull/1129 as a duplicate of this PR, because 1.) This PR was opened first, and 2.) In this PR, the import is added in alphabetical order. We will merged this PR.

**Review by neethajohn — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Pull request merged**
