### PR TITLE
[portstat] check TX/RX utilization calculation correctness

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
#### What I did
Update test for checking TX/RX utilization

#### How I did it
Add real values for TX/RX to mock table instead of zeroes 

#### How to verify it
run **portstat_test.py** via  `python3 setup.py test`  in  sonic-utilities tests 

#### New command output (if the output of a command-line utility has changed)

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@ayurkiv-nvda could you please specify on which branches this fix should be taken?
@qiluo-msft or @lguohan could you please recommend a reviewer?

**Comment by ayurkiv-nvda** [comment]
> @ayurkiv-nvda could you please specify on which branches this fix should be taken? @qiluo-msft or @lguohan could you please recommend a reviewer?

Problem related to this fix appeared  after merging [1750](https://github.com/Azure/sonic-utilities/pull/1750)
Currently it is related only to **202106** branch but maybe I will double check it

**Comment by liat-grozovik** [comment]
@qiluo-msft any further comments on this PR that should be followed?

**Comment by liat-grozovik** [comment]
@qiluo-msft kindly reminder. Can you please review?

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
