### PR TITLE
[consutil][test] Add unit tests for consutil clear command

### PR DESCRIPTION
**Pull request by Blueve**
**- What I did**
Add unit tests for `consutil clear` command.

**- How I did it**
Write unit test cases.

**- How to verify it**
Run unit tests locally and all pass.
```
Name                                       Stmts   Miss  Cover
--------------------------------------------------------------
consutil/lib.py                              218      8    96%
consutil/main.py                              67      4    94%
```

**- Previous command output (if the output of a command-line utility has changed)**
N/A

**- New command output (if the output of a command-line utility has changed)**
N/A

### CODE REVIEW

**Comment by Blueve** [comment]
retest default please

**Comment by Blueve** [comment]
retest all please

**Review by yxieca — APPROVED** [review]
There are some unrelated test failures?

**Comment by Blueve** [comment]
> There are some unrelated test failures?

Yes, unrelated. All tests are passed locally.

**Pull request merged**
