### PR TITLE
Update `config mirror_session` CLI to support heximal gre type value

### PR DESCRIPTION
**Pull request by bingwang-ms**
Signed-off-by: bingwang <bingwang@microsoft.com>

#### What I did
Fix https://github.com/Azure/sonic-buildimage/issues/10096
This PR is to update CLI for `config mirror_session add` to support heximal gre type value.
Change in YANG model https://github.com/Azure/sonic-buildimage/pull/10140
#### How I did it
Add a validator for gre_type. Now both hexadecimal and decimal values are accepted.

#### How to verify it
1. Verified by UT
2. Verified by copying the updated `main.py` to a testbed and manual verification.

#### Previous command output (if the output of a command-line utility has changed)
No change in output.

#### New command output (if the output of a command-line utility has changed)
No change in output.

### CODE REVIEW

**Review by liat-grozovik — APPROVED** [review]

**Comment by dgsudharsan** [comment]
@bingwang-ms Can you please sync to the latest? Recent builds have vstest disabled

**Comment by bingwang-ms** [comment]
> @bingwang-ms Can you please sync to the latest? Recent builds have vstest disabled

Syncd. Let's wait the next PR check

**Pull request merged**
