### PR TITLE
Replace swsssdk.SonicV2Connector with swsscommon.SonicV2Connector (SWIG wrapper of C++ implementation) in production code

### PR DESCRIPTION
**Pull request by qiluo-msft**
**- What I did**
This is the following step for merging sonic-py-swsssdk into sonic-swss-common https://github.com/Azure/sonic-swss-common/pull/387

**- How I did it**

**- How to verify it**
Unit test and tested in DUT

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Review by tahmed-dev — DISMISSED** [review]

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by qiluo-msft** [comment]
Retest this please

**Review by jleveque — DISMISSED** [review]

**Review by tahmed-dev — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Retest this please

**Pull request merged**
