### PR TITLE
[debug dump util] Techsupport addition

### PR DESCRIPTION
**Pull request by vivekreddynv**
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

**DEBUG DUMP UTIL PR SEQ: 4**

**NOTE: PLEASE MERGE #1668  BEFORE MERGING THIS**

#### What I did

HLD for Dump Utility: [HLD](https://github.com/Azure/SONiC/pull/789).
For More info on Tech Support Addition: [TechSupport](https://github.com/Azure/SONiC/blob/fda816c24570df33f253e525bb3fee7ae72fa431/doc/Dump-Utility.md#4-techsupport)

#### How I did it

Module Names are retrieved by parsing the output of dump state --show command.

Eg: 
```
root@sonic:~# dump state  --help
Usage: dump state [OPTIONS] MODULE IDENTIFIER

  Dump the redis-state of the identifier for the module specified

Options:
............
 -s, --show            Display Modules Available
............

root@sonic:~$ dump state --show
Module    Identifier
--------  ------------
copp      trap_id
port      port_name
```

#### How to verify it

```
root@sonic-dev:~# show techsupport --debug-dump
root@sonic-dev:~# tar -xvzf /var/dump/sonic_dump_sonic-dev-69_20210525_055031.tar.gz
root@sonic-dev:~/sonic_dump_sonic-dev-69_20210525_055031# ls -l dump/ | grep unified_view
drwxr-xr-x 2 root root    4096 May 25 06:05 unified_view_dump
root@sonic-dev:~/sonic_dump_sonic-dev-69_20210525_055031# cd dump/unified_view_dump/
root@sonic-dev:~/sonic_dump_sonic-dev-69_20210525_055031/dump/unified_view_dump# ls
copp  port
root@sonic-dev:~/sonic_dump_sonic-dev-69_20210525_055031/dump/unified_view_dump# cat port

"Ethernet192": {
        "CONFIG_DB": {
            "keys": [
                "PORT|Ethernet192"
            ],
            "tables_not_found": []
        },
        "APPL_DB": {
            "keys": [
                "PORT_TABLE:Ethernet192"
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                "ASIC_STATE:SAI_OBJECT_TYPE_HOSTIF:oid:0xd000000000585",
                "ASIC_STATE:SAI_OBJECT_TYPE_PORT:oid:0x10000000002f7"
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0xd000000000585": "oid:0x180000000d",
                "oid:0x10000000002f7": "oid:0x1350000000001"
            }
        },
        "STATE_DB": {
            "keys": [
                "PORT_TABLE|Ethernet192"
            ],
            "tables_not_found": []
        }
    },
    "Ethernet64": {
        "CONFIG_DB": {
            "keys": [
                "PORT|Ethernet64"
            ],
            "tables_not_found": []
        },
        "APPL_DB": {
            "keys": [
                "PORT_TABLE:Ethernet64"
            ],
            "tables_not_found": []
        },
        "ASIC_DB": {
            "keys": [
                "ASIC_STATE:SAI_OBJECT_TYPE_HOSTIF:oid:0xd000000000575",
                "ASIC_STATE:SAI_OBJECT_TYPE_PORT:oid:0x1000000000420"
            ],
            "tables_not_found": [],
            "vidtorid": {
                "oid:0xd000000000575": "oid:0x80000000d",
                "oid:0x1000000000420": "oid:0x1590000000001"
            }
        },
        "STATE_DB": {
            "keys": [
                "PORT_TABLE|Ethernet64"
            ],
            "tables_not_found": []
        }
    },
    <Truncated>
```

### CODE REVIEW

**Comment by vivekreddynv** [comment]
Request for 202106

**Review by SuvarnaMeenakshi — APPROVED** [review]
lgtm

**Comment by vivekreddynv** [comment]
> lgtm

Changes in latest commit: made the collection of debug dump configurable in techsupport and is not enabled by default

**Comment by vivekreddynv** [comment]
@SuvarnaMeenakshi, Can you sign-off this pr?

**Pull request merged**
