### PR TITLE
Change ip-helper address in CLI and show to verify

### PR DESCRIPTION
**Pull request by samaity**
Signed-off-by: Sangita Maity <sangitamaity0211@gmail.com>

**- What I did**
Introducing **dhcp_relay** subbcommand under vlan command to change dhcp-relay ip-helper address via **config** CLI and verify using **show** CLI command.

**- How I did it**
using config db
**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**
                     Introducing new subcommands. N/A
**- New command output (if the output of a command-line utility has changed)**

**admin@lnos-x1-a-csw04:/usr/lib/python2.7/dist-packages$ sudo config vlan dhcp_relay --help**
Usage: config vlan dhcp_relay [OPTIONS] <helper_ip> <vid>
Options:
  --help  Show this message and exit.

_if vid is mentioned , it will take particular vlan id. Otherwise, it will consider for all vlans by default._
```
**admin@lnos-x1-a-csw04:~$ show dhcp_relay vlan**   _---> Before the changing helper ip address_
VLAN ID    HELPER IP
Vlan100    10.189.64.1
Vlan777    10.189.64.1
```

**Changed ip-helper address of one vlan specifying vlan id (i.e. 100) using config command CLI**
```
admin@lnos-x1-a-csw04:/usr/lib/python2.7/dist-packages$ sudo config vlan dhcp_relay 1.2.3.4 100
Running command: service dhcp_relay restart

### Verification
admin@lnos-x1-a-csw04:/usr/lib/python2.7/dist-packages$ show dhcp_relay vlan
VLAN ID    HELPER IP
Vlan100    1.2.3.4
Vlan777    10.189.64.1
```
**Changed ip-helper address of all vlans present in config db using config command CLI.**
```
**_admin@lnos-x1-a-csw04:/usr/lib/python2.7/dist-packages$ sudo config vlan dhcp_relay 10.10.11.11_**
Running command: service dhcp_relay restart

### Verification
**_admin@lnos-x1-a-csw04:/usr/lib/python2.7/dist-packages$ show dhcp_relay vlan_**
VLAN ID    HELPER IP
Vlan100    10.10.11.11
Vlan777    10.10.11.11
```

### Verification of  show commands
```
admin@lnos-x1-a-csw04:~$ show dhcp_relay
Usage: show dhcp_relay [OPTIONS] COMMAND [ARGS]...
Show dhcp-relay helper ip for all vlan

Options:
  -?, -h, --help  Show this message and exit.
Commands:
  vlan  Show dhcp-relay helper ip for a vlan


### show dhcp_relay command
**admin@lnos-x1-a-csw04:~$ show dhcp_relay vlan**
VLAN ID    HELPER IP
Vlan100    10.10.11.11
Vlan777    10.10.11.11

admin@lnos-x1-a-csw04:~$ show dhcp_relay vlan 100
VLAN ID    HELPER IP
Vlan100    10.10.11.11

admin@lnos-x1-a-csw04:~$ show dhcp_relay vlan 777
VLAN ID    HELPER IP
Vlan777    10.10.11.11
```
### Result of test case when the user-specified VLAN does not exist ->
```
admin@lnos-x1-a-csw04:~$ sudo config vlan dhcp_relay 1.1.1.1 300
Usage: config vlan dhcp_relay [OPTIONS] <helper_ip> <vid>

Error: Vlan300 doesn't exist

### Result of test case for no VLAN configured ->

admin@lnos-x1-a-csw04:/usr/lib/python2.7/dist-packages$ sudo config vlan dhcp_relay 1.1.1.1
Usage: config vlan dhcp_relay [OPTIONS] <helper_ip> <vid>

Error: No VLAN is configured yet

```

### CODE REVIEW

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by stcheng** [comment]
retest this please

**Comment by samaity** [comment]
> Please replace all tabs with spaces.

done

**Comment by jleveque** [comment]
As requested above, please also update the documentation at https://github.com/Azure/sonic-utilities/blob/master/doc/Command-Reference.md to reflect these changes.

**Comment by samaity** [comment]
https://github.com/Azure/sonic-utilities/pull/585

already added to the repo. closing it.

**Pull request closed without merging**
