### PR TITLE
[show]: Add 'show interfaces alias' command to display port name/alias mapping

### PR DESCRIPTION
**Pull request by jleveque**
Sample output:

```
admin@sonic:~$ show interfaces alias
Name         Alias
-----------  --------------
Ethernet0    fortyGigE0/0
Ethernet4    fortyGigE0/4
Ethernet8    fortyGigE0/8
Ethernet12   fortyGigE0/12
Ethernet16   fortyGigE0/16
Ethernet20   fortyGigE0/20
Ethernet24   fortyGigE0/24
Ethernet28   fortyGigE0/28
Ethernet32   fortyGigE0/32
Ethernet36   fortyGigE0/36
Ethernet40   fortyGigE0/40
Ethernet44   fortyGigE0/44
Ethernet48   fortyGigE0/48
Ethernet52   fortyGigE0/52
Ethernet56   fortyGigE0/56
Ethernet60   fortyGigE0/60
Ethernet64   fortyGigE0/64
Ethernet68   fortyGigE0/68
Ethernet72   fortyGigE0/72
Ethernet76   fortyGigE0/76
Ethernet80   fortyGigE0/80
Ethernet84   fortyGigE0/84
Ethernet88   fortyGigE0/88
Ethernet92   fortyGigE0/92
Ethernet96   fortyGigE0/96
Ethernet100  fortyGigE0/100
Ethernet104  fortyGigE0/104
Ethernet108  fortyGigE0/108
Ethernet112  fortyGigE0/112
Ethernet116  fortyGigE0/116
Ethernet120  fortyGigE0/120
Ethernet124  fortyGigE0/124
```
```
admin@sonic:~$ show interfaces alias Ethernet44
Name        Alias
----------  -------------
Ethernet44  fortyGigE0/44
```

### CODE REVIEW

**Comment by jleveque** [comment]
@nikos-li: Sample output added to PR description.

**Comment by nikos-li** [comment]
show interface portmap does the same thing. Why do we need yet another command?

**Comment by jleveque** [comment]
@nikos-li: SONiC does not have a `show interface portmap` command. What are you referring to?

**Comment by nikos-li** [comment]
@jleveque It is up for review, isn't it? https://github.com/Azure/sonic-utilities/pull/98

**Comment by jleveque** [comment]
@nikos-li: That PR is held up due to the debate over the `Clear` command. Also, this solution is cleaner as it doesn't require the writing of template files. If you prefer the command name `portmap` over `alias`, please open a new issue and we can discuss it there.

**Comment by nikos-li** [comment]
@jleveque You could have suggested those changes in show interface portmap if you thought it was a better solution. Merging code that hasn't been cleared from all reviewers, is not acceptable. Especially when a solution for the same issue is in review.

**Pull request merged**
