### PR TITLE
Add check to not allow deleting PO if its member of vlan.

### PR DESCRIPTION
**Pull request by anilkpan**
#### What I did
Added check to not allow deleting PortChannel if its member of vlan.
#### How I did it
Added a check in the command script.
#### How to verify it
1. Create a portchannel.
2. Add the portchannel to a vlan.
3. Try to delete the portchannel.
4. It should throw an error message.
#### New command output (if the output of a command-line utility has changed)
Error: PortChannel1 has vlan Vlan100 configured, remove vlan membership to proceed

### CODE REVIEW

**Comment by anilkpan** [comment]
Fixes issue #10388

**Review by dgsudharsan — CHANGES_REQUESTED** [review]
Can you please add UT for coverage?

**Comment by anilkpan** [comment]
I am working on adding UT coverage

**Comment by anilkpan** [comment]
@dprital, I plan to add the tests by the end of the week.

**Review by prsunny — APPROVED** [review]

**Review by dgsudharsan — DISMISSED** [review]

**Comment by dgsudharsan** [comment]
@anilkpan  Can you please review the pipeline failures?

**Comment by anilkpan** [comment]
@dgsudharsan, I am looking at the failures.

**Comment by anilkpan** [comment]
PortChannel creation was successful, but it says portchannel doesn't exist when trying to add to vlan. Not sure how to fix this.

        # add a portchannel
        result = runner.invoke(config.config.commands["portchannel"].commands["add"], ["PortChannel1005"], obj=obj)
        print(result.exit_code)
        print(result.output)
        assert result.exit_code == 0
    
        # add portchannel to a vlan
        result = runner.invoke(config.config.commands["vlan"].commands["member"].commands["add"], ["2000", "PortChannel1005"], obj=obj)
        print(result.exit_code)
        print(result.output)
>       assert result.exit_code == 0
E       assert 2 == 0
E        +  where 2 = <Result SystemExit(2)>.exit_code

tests/portchannel_test.py:197: AssertionError
----------------------------- Captured stdout call -----------------------------
0

2
Usage: add [OPTIONS] <vid> port
Try "add --help" for help.

Error: PortChannel1005 does not exist

**Comment by dgsudharsan** [comment]
> > ```
> >   assert result.exit_code == 0
> > ```

Were you able to debug further? I believe you need to have portchannel as a member here https://github.com/Azure/sonic-utilities/blob/6a327adf6b55faed8c4f6ddfb8bde6f80efbef2d/tests/mock_tables/config_db.json. The config commands here may not modify the DB.
Please add vlan and portchannel in the file. Try to perform only remove and check if it helps.

**Comment by anilkpan** [comment]
@dgsudharsan, Thanks. I will try this.

**Review by prsunny — APPROVED** [review]

**Comment by yxieca** [comment]
@dgsudharsan this PR cannot be cherry-picked cleanly to 202205. please open PR if needed in 202205.

**Comment by dgsudharsan** [comment]
@anilkpan  Can you please raise a backport PR to 202205 branch?

**Comment by anilkpan** [comment]
@dgsudharsan, will create the PR this week.

**Comment by yxieca** [comment]
@dgsudharsan , @anilkpan do you have ETA for the 202205 PR?

**Comment by anilkpan** [comment]
@yxieca, I plan to create the PR by Monday.

**Comment by anilkpan** [comment]
Created PR https://github.com/Azure/sonic-utilities/pull/2237

**Comment by dgsudharsan** [comment]
@anilkpan Thanks. However I see this PR in master has a binary file [.DS_Store](https://github.com/Azure/sonic-utilities/pull/2141/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86). Was this added by mistake? Can you please remove it?

**Comment by anilkpan** [comment]
@dgsudharsan, yes it was added by mistake, will remove it.

**Pull request merged**
