### PR TITLE
[sonic_sku_create] Move tests from sonic-utilities-tests/ folder to tests/ folder

### PR DESCRIPTION
**Pull request by madhanmellanox**
**- What I did**
I moved all files currently in sonic-utilities-tests folder to tests folder of sonic-utilities repository.

**- How I did it**
I add the files to tests folder using git add and did a git rm from sonic-uitlities-tests folder.

**- How to verify it**
After the commit, verify if the sonic-utilities-tests folder is removed in the repository and all the files are moved to tests folder.
**- Previous command output (if the output of a command-line utility has changed)**
None

**- New command output (if the output of a command-line utility has changed)**
None

### CODE REVIEW

**Comment by madhanmellanox** [comment]
retest this please

**Comment by lguohan** [comment]
check the error. 

11:15:50  output = "/usr/bin/env: 'python2': No such file or directory\n"

are you hardcoding python2 in the test?

**Comment by madhanmellanox** [comment]
retest default

**Comment by madhanmellanox** [comment]
retest this please

**Comment by madhanmellanox** [comment]
@lguohan it was a code review comment to change the shebang line to python2.

**Comment by madhanmellanox** [comment]
@jleveque can you please review and approve this?

**Review by jleveque — APPROVED** [review]

**Pull request merged**
