### PR TITLE
[201911][show] Fix 'show int neigh expected'

### PR DESCRIPTION
**Pull request by lolyu**
`show int neighbor expected` only show one member interface for
portchannel with multiple member interfaces. This is because
`device2interface_dict` only stores mapping from one device to one
port.

Signed-off-by: Longxiang Lyu <lolv@microsoft.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**
```
$ show int neighbor expected
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet64   ARISTA01T0  Ethernet1       None                10.64.247.144   ToRRouter
Ethernet4    ARISTA01T2  Ethernet2       None                10.64.247.136   SpineRouter
Ethernet68   ARISTA02T0  Ethernet1       None                10.64.247.145   ToRRouter
Ethernet72   ARISTA03T0  Ethernet1       None                10.64.247.146   ToRRouter
Ethernet12   ARISTA03T2  Ethernet2       None                10.64.247.137   SpineRouter
Ethernet76   ARISTA04T0  Ethernet1       None                10.64.247.147   ToRRouter
Ethernet80   ARISTA05T0  Ethernet1       None                10.64.247.148   ToRRouter
Ethernet20   ARISTA05T2  Ethernet2       None                10.64.247.138   SpineRouter
Ethernet84   ARISTA06T0  Ethernet1       None                10.64.247.149   ToRRouter
Ethernet88   ARISTA07T0  Ethernet1       None                10.64.247.150   ToRRouter
Ethernet28   ARISTA07T2  Ethernet2       None                10.64.247.139   SpineRouter
Ethernet92   ARISTA08T0  Ethernet1       None                10.64.247.151   ToRRouter
Ethernet96   ARISTA09T0  Ethernet1       None                10.64.247.152   ToRRouter
Ethernet36   ARISTA09T2  Ethernet2       None                10.64.247.140   SpineRouter
Ethernet100  ARISTA10T0  Ethernet1       None                10.64.247.153   ToRRouter
Ethernet104  ARISTA11T0  Ethernet1       None                10.64.247.154   ToRRouter
Ethernet44   ARISTA11T2  Ethernet2       None                10.64.247.141   SpineRouter
Ethernet108  ARISTA12T0  Ethernet1       None                10.64.247.155   ToRRouter
Ethernet112  ARISTA13T0  Ethernet1       None                10.64.247.156   ToRRouter
Ethernet52   ARISTA13T2  Ethernet2       None                10.64.247.142   SpineRouter
Ethernet116  ARISTA14T0  Ethernet1       None                10.64.247.157   ToRRouter
Ethernet120  ARISTA15T0  Ethernet1       None                10.64.247.158   ToRRouter
Ethernet60   ARISTA15T2  Ethernet2       None                10.64.247.143   SpineRouter
Ethernet124  ARISTA16T0  Ethernet1       None                10.64.247.159   ToRRouter
```
**- New command output (if the output of a command-line utility has changed)**
```
$ show int neighbor expected
LocalPort    Neighbor    NeighborPort    NeighborLoopback    NeighborMgmt    NeighborType
-----------  ----------  --------------  ------------------  --------------  --------------
Ethernet0    ARISTA01T2  Ethernet1       None                10.64.247.136   SpineRouter
Ethernet4    ARISTA01T2  Ethernet2       None                10.64.247.136   SpineRouter
Ethernet8    ARISTA03T2  Ethernet1       None                10.64.247.137   SpineRouter
Ethernet12   ARISTA03T2  Ethernet2       None                10.64.247.137   SpineRouter
Ethernet16   ARISTA05T2  Ethernet1       None                10.64.247.138   SpineRouter
Ethernet20   ARISTA05T2  Ethernet2       None                10.64.247.138   SpineRouter
Ethernet24   ARISTA07T2  Ethernet1       None                10.64.247.139   SpineRouter
Ethernet28   ARISTA07T2  Ethernet2       None                10.64.247.139   SpineRouter
Ethernet32   ARISTA09T2  Ethernet1       None                10.64.247.140   SpineRouter
Ethernet36   ARISTA09T2  Ethernet2       None                10.64.247.140   SpineRouter
Ethernet40   ARISTA11T2  Ethernet1       None                10.64.247.141   SpineRouter
Ethernet44   ARISTA11T2  Ethernet2       None                10.64.247.141   SpineRouter
Ethernet48   ARISTA13T2  Ethernet1       None                10.64.247.142   SpineRouter
Ethernet52   ARISTA13T2  Ethernet2       None                10.64.247.142   SpineRouter
Ethernet56   ARISTA15T2  Ethernet1       None                10.64.247.143   SpineRouter
Ethernet60   ARISTA15T2  Ethernet2       None                10.64.247.143   SpineRouter
Ethernet64   ARISTA01T0  Ethernet1       None                10.64.247.144   ToRRouter
Ethernet68   ARISTA02T0  Ethernet1       None                10.64.247.145   ToRRouter
Ethernet72   ARISTA03T0  Ethernet1       None                10.64.247.146   ToRRouter
Ethernet76   ARISTA04T0  Ethernet1       None                10.64.247.147   ToRRouter
Ethernet80   ARISTA05T0  Ethernet1       None                10.64.247.148   ToRRouter
Ethernet84   ARISTA06T0  Ethernet1       None                10.64.247.149   ToRRouter
Ethernet88   ARISTA07T0  Ethernet1       None                10.64.247.150   ToRRouter
Ethernet92   ARISTA08T0  Ethernet1       None                10.64.247.151   ToRRouter
Ethernet96   ARISTA09T0  Ethernet1       None                10.64.247.152   ToRRouter
Ethernet100  ARISTA10T0  Ethernet1       None                10.64.247.153   ToRRouter
Ethernet104  ARISTA11T0  Ethernet1       None                10.64.247.154   ToRRouter
Ethernet108  ARISTA12T0  Ethernet1       None                10.64.247.155   ToRRouter
Ethernet112  ARISTA13T0  Ethernet1       None                10.64.247.156   ToRRouter
Ethernet116  ARISTA14T0  Ethernet1       None                10.64.247.157   ToRRouter
Ethernet120  ARISTA15T0  Ethernet1       None                10.64.247.158   ToRRouter
Ethernet124  ARISTA16T0  Ethernet1       None                10.64.247.159   ToRRouter
```

### CODE REVIEW

**Comment by lolyu** [comment]
Retest this please

**Comment by lguohan** [comment]
is this the downport of pr #1162

**Review by lguohan — APPROVED** [review]

**Comment by lolyu** [comment]
> is this the downport of pr #1162
Yes, can #1162 be cherry-picked into `201911`? If yes, I will close this one.

**Comment by lguohan** [comment]
no it cannot.

**Comment by lguohan** [comment]
retest this please

**Comment by lolyu** [comment]
Retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lolyu** [comment]
retest this please

**Comment by lolyu** [comment]
retest this please

**Comment by lguohan** [comment]
@jleveque , is 201911 unit test broken now?

**Comment by jleveque** [comment]
> @jleveque , is 201911 unit test broken now?

Unfortunately, yes, the check build is broken for 201911 becuase it is shared with master, and it has been changed to build and test as a wheel in master, but it is still built as a Debian package in 201911.

**Comment by lguohan** [comment]
the code has no issue. unit test is not working for 201911 branch.

**Pull request merged**
