### PR TITLE
sonic_utilities: Support for DOM Threshold values for EEPROM dump

### PR DESCRIPTION
**Pull request by sridhar-ravindran**
**- What I did**
Added support to dump Dom Threshold values along with other dom values as per EEPROM sff8436 standard.
**- How I did it**
Read the eeprom,  save the redis transceiver_dom table with threshold values.

**- How to verify it**
sfpshow eeprom --dom
**- Previous command output (if the output of a command-line utility has changed)**
Ethernet124: SFP EEPROM detected
        Connector: MPOx12
        Encoding: 64B66B
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+ or later
        Length OM3(2m): 50
        Nominal Bit Rate(100Mbs): 103
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-SR4
        Vendor Date Code(YYYY-MM-DD Lot): 2010-09-01
        Vendor Name: AVAGO
        Vendor OUI: 00-17-6a
        Vendor PN: AFBR-79E4Z-D
        Vendor Rev: 01
        Vendor SN: QA340092
        ChannelMonitorValues:
                RX1Power: -16.3827dBm
                RX2Power: -infdBm
                RX3Power: -15.5284dBm
                RX4Power: -infdBm
                TX1Bias: 5.9720mA
                TX2Bias: 5.3740mA
                TX3Bias: 5.3800mA
                TX4Bias: 6.0540mA
        ModuleMonitorValues:
                Temperature: 32.4688C
                Vcc: 3.3458Volts

**- New command output (if the output of a command-line utility has changed)**
Ethernet124: SFP EEPROM detected
        Connector: MPOx12
        Encoding: 64B66B
        Extended Identifier: Power Class 1(1.5W max)
        Extended RateSelect Compliance: QSFP+ Rate Select Version 1
        Identifier: QSFP+ or later
        Length OM3(2m): 50
        Nominal Bit Rate(100Mbs): 103
        Specification compliance:
                10/40G Ethernet Compliance Code: 40GBASE-SR4
        Vendor Date Code(YYYY-MM-DD Lot): 2010-09-01
        Vendor Name: AVAGO
        Vendor OUI: 00-17-6a
        Vendor PN: AFBR-79E4Z-D
        Vendor Rev: 01
        Vendor SN: QA340092
        ChannelMonitorValues:
                RX1Power: -16.3827dBm
                RX2Power: -infdBm
                RX3Power: -15.5284dBm
                RX4Power: -infdBm
                TX1Bias: 5.9720mA
                TX2Bias: 5.3740mA
                TX3Bias: 5.3800mA
                TX4Bias: 6.0540mA
        ChannelThresholdValues:
                RxPowerHighAlarm    : 3.4001dBm
                RxPowerHighWarning: 2.4000dBm
                RxPowerLowAlarm     : -13.5067dBm
                RxPowerLowWarning : -9.5001dBm
                TxBiasHighAlarm        : 10.0000mA
                TxBiasHighWarning    : 9.5000mA
                TxBiasLowAlarm         : 0.5000mA
                TxBiasLowWarning     : 1.0000mA
        ModuleMonitorValues:
                Temperature: 32.4688C
                Vcc: 3.3458Volts
        ModuleThresholdValues:
                TempHighAlarm    : 75.0000C
                TempHighWarning: 70.0000C
                TempLowAlarm     : -5.0000C
                TempLowWarning : 0.0000C
                VccHighAlarm       : 3.6300Volts
                VccHighWarning   : 3.4650Volts
                VccLowAlarm        : 2.9700Volts
                VccLowWarning    : 3.1349Volts

-->

### CODE REVIEW

**Comment by sridhar-ravindran** [comment]
Depends on 
https://github.com/Azure/sonic-platform-common/pull/33

**Comment by sridhar-ravindran** [comment]
[S6100_UnitTesting.txt](https://github.com/Azure/sonic-utilities/files/3233889/S6100_UnitTesting.txt)
[z9100_50G_breakout_profile.log](https://github.com/Azure/sonic-utilities/files/3233890/z9100_50G_breakout_profile.log)
[Uploading Finisar_dell_avago_Eeprom_dom_dump.log…]()
[Uploading Z9100_UnitTesting.txt…]()

**Comment by jleveque** [comment]
@keboliu: Please review

**Comment by keboliu** [comment]
> @keboliu: Please review

@sridhar-ravindran  @jleveque, please check the comments I raised in the two dependencies PRs.

**Comment by sridhar-ravindran** [comment]
Hi @keboliu

I have rebased to latest master. Please review.

Thanks
Sridhar.R

**Comment by sridhar-ravindran** [comment]
Hi @keboliu @jleveque 
Could you please review and approve this . This is also needed for DOM Threshold values.
Thanks
Sridhar.R

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
@sridhar-ravindran: I'm sorry, but there are now conflicts. Can you please fix them?

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Pull request merged**
