### PR TITLE
[master]Fix import lib issue

### PR DESCRIPTION
**Pull request by tim-rj**
**- What I did**
show interface breakout
**- How I did it**
```
show interface breakout
```
**- How to verify it**
```
show interface breakout
```

**- Previous command output (if the output of a command-line utility has changed)**
```
root@sonic:/var/core# show interfaces breakout 
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/interfaces/__init__.py", line 118, in breakout
    config_db = ConfigDBConnector()
NameError: global name 'ConfigDBConnector' is not defined
```
**- New command output (if the output of a command-line utility has changed)**

```
No import error, just notify  platform.json not exist.
root@switch2:/usr/lib/python2.7/dist-packages/show/interfaces# show interfaces breakout
[Errno 2] No such file or directory: '/usr/share/sonic/device/x86_64-ruijie_b3010-r0/platform.json'
Aborted!
```

### CODE REVIEW

**Comment by tim-rj** [comment]
It is related to issue:https://github.com/Azure/sonic-buildimage/issues/5343

**Comment by tim-rj** [comment]
Any one can help forward?

**Comment by lguohan** [comment]
can you only include the changes needed by the fix?

**Comment by tim-rj** [comment]
> 
> 
> can you only include the changes needed by the fix?
if only import missing libs(remove added global vars & function), 'show interface breakout' will still fail, do I still need to remove the vars & function? Help confirm, waiting reply .

**Comment by tim-rj** [comment]
move to a new PR https://github.com/Azure/sonic-utilities/pull/1179 for refolk the component, close this one.

**Pull request closed without merging**
