### PR TITLE
[CLI][show bgp] On chassis don't show internal BGP sessions by default

### PR DESCRIPTION
**Pull request by smaheshm**
#### What I did
Similar to multi ASIC platform, on chassis don't show internal BGP sessions by default

Unit tests rely on output of 'show ip bgp summary' to check BGP status. Since the original output included internal BGP sessions BGP status check fails as internal sessions are never brought down.

#### How I did it
perform internal BGP session on chassis

Requires https://github.com/Azure/sonic-buildimage/pull/9264

#### How to verify it
```
admin@str2-chassis-lc3-1:~$ show ip bgp summary

IPv4 Unicast Summary:
BGP router identifier 192.0.0.3, local AS number 65100 vrf-id 0
BGP table version 8576
RIB entries 17069, using 3277248 bytes of memory
Peers 21, using 458136 KiB of memory
Peer groups 2, using 128 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.0.1       4  65200       1190       1190         0      0       0  00:45:57   8513            ARISTA01T3
10.0.0.9       4  65200          0          0         0      0       0  never      Active          ARISTA05T3
10.0.0.13      4  65200          0          0         0      0       0  never      Active          ARISTA07T3
10.0.0.17      4  65200          0          0         0      0       0  never      Active          ARISTA09T3
10.0.0.21      4  65200          0          0         0      0       0  never      Active          ARISTA11T3
10.0.0.25      4  65200          0          0         0      0       0  never      Active          ARISTA13T3
.
.


admin@str2-chassis-lc3-1:~$ show ip bgp summary -d all

IPv4 Unicast Summary:
BGP router identifier 10.3.147.15, local AS number 65100 vrf-id 0
BGP table version 8623
RIB entries 17107, using 3284544 bytes of memory
Peers 23, using 501768 KiB of memory
Peer groups 3, using 192 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  ---------------
3.3.3.6        4  65100          0          0         0      0       0  never      Active          str2-chassis-lc6-1
3.3.3.7        4  65100         44       8570         0      0       0  00:30:54   20              str2-chassis-lc7-1
10.0.0.1       4  65200       4879       4880         0      0       0  00:30:52   8514            ARISTA01T3
10.0.0.9       4  65202          0          0         0      0       0  never      Active          ARISTA05T3
10.0.0.13      4  65203          0          0         0      0       0  never      Connect         ARISTA07T3
10.0.0.17      4  65204          0          0         0      0       0  never      Connect         ARISTA09T3


```

#### Previous command output (if the output of a command-line utility has changed)

```

admin@str2-chassis-lc3-1:~$ show ip bgp summary

IPv4 Unicast Summary:
BGP router identifier 10.3.147.15, local AS number 65100 vrf-id 0
BGP table version 8623
RIB entries 17107, using 3284544 bytes of memory
Peers 23, using 501768 KiB of memory
Peer groups 3, using 192 bytes of memory


Neighbhor      V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
-----------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  ---------------
3.3.3.6        4  65100          0          0         0      0       0  never      Active          str2-chassis-lc6-1
3.3.3.7        4  65100         44       8570         0      0       0  00:30:54   20              str2-chassis-lc7-1
10.0.0.1       4  65200       4879       4880         0      0       0  00:30:52   8514            ARISTA01T3
10.0.0.9       4  65202          0          0         0      0       0  never      Active          ARISTA05T3
10.0.0.13      4  65203          0          0         0      0       0  never      Connect         ARISTA07T3
10.0.0.17      4  65204          0          0         0      0       0  never      Connect         ARISTA09T3

```
```

#### New command output (if the output of a command-line utility has changed)

### CODE REVIEW

**Comment by smaheshm** [comment]
needs https://github.com/Azure/sonic-buildimage/pull/9290 to pass the builds.

**Comment by arlakshm** [comment]
@ysmanman, @vganesan-nokia  for viz

**Review by arlakshm — APPROVED** [review]
lgtm

**Pull request merged**
