### PR TITLE
[generate_dump] Dump systemd specific information

### PR DESCRIPTION
**Pull request by Staphylo**
**- What I did**

Added some extra save_cmd in generate_dump to grab systemd specific information
 - dump: dumps the entire state of all the units
 - blame: provides startup time for each service
 - plot: generate a svg of the boot order

**- How to verify it**

Simply run generate_dump and look for the 3 new files
-->

### CODE REVIEW

**Comment by Staphylo** [comment]
Build failed with `java.lang.OutOfMemoryError: Java heap space` how to rebuild ?

**Comment by jleveque** [comment]
@Staphylo: You can trigger a rebuild by commenting "Retest this please"

**Comment by Staphylo** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Pull request merged**
