### PR TITLE
Updates to bgp config and show commands with BGP_INTERNAL_NEIGHBOR table

### PR DESCRIPTION
**Pull request by judyjoseph**
**- What I did**
Updates to bgp config and show commands with the movement of internal bgp sessions to a new table BGP_INTERNAL_NEIGHBOR table. 
With the introduction of BGP_INERNAL_NEIGHBOR table, the user cannot start/stop/remove internal neighbors which I feel is not needed as these internal bgp sessions which are supposed to be UP allways.

**- How I did it**
Updated the show/bgp util so that it gets the internal bgp sessions from BGP_INTERNAL_NEIGHBOR table.
Removed the API's to get the local_as in config/bgp which is not required now. 

**- How to verify it**
Made sure that the output remain same with the new internal bgp neighbor table.
```

admin@:~$ show ip bgp summary  

IPv4 Unicast Summary:
asic0: BGP router identifier 10.0.107.16, local AS number 65100 vrf-id 0
BGP table version 21
asic1: BGP router identifier 10.0.107.17, local AS number 65100 vrf-id 0
BGP table version 24
asic2: BGP router identifier 10.0.107.18, local AS number 65100 vrf-id 0
BGP table version 21
asic3: BGP router identifier 10.0.107.19, local AS number 65100 vrf-id 0
BGP table version 24
RIB entries 116, using 21344 bytes of memory
Peers 32, using 669440 KiB of memory
Peer groups 16, using 1024 bytes of memory


Neighbhor       V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
------------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.10.192.33    4  64001          0          0         0      0       0  never      Idle (Admin)    ARISTA01T0
10.10.192.35    4  64002          0          0         0      0       0  never      Idle (Admin)    ARISTA02T0
10.10.192.37    4  64003          0          0         0      0       0  never      Idle (Admin)    ARISTA03T0
10.10.192.39    4  64004          0          0         0      0       0  never      Idle (Admin)    ARISTA04T0
10.10.192.41    4  64005          0          0         0      0       0  never      Idle (Admin)    ARISTA05T0
10.10.192.43    4  64006          0          0         0      0       0  never      Idle (Admin)    ARISTA06T0
10.10.192.45    4  64007          0          0         0      0       0  never      Idle (Admin)    ARISTA07T0
10.10.192.47    4  64008          0          0         0      0       0  never      Idle (Admin)    ARISTA08T0
10.10.192.49    4  64009          0          0         0      0       0  never      Idle (Admin)    ARISTA09T0
10.10.192.51    4  64010          0          0         0      0       0  never      Idle (Admin)    ARISTA10T0
10.10.192.53    4  64011          0          0         0      0       0  never      Idle (Admin)    ARISTA11T0
10.10.192.55    4  64012          0          0         0      0       0  never      Idle (Admin)    ARISTA12T0
10.10.192.57    4  64013          0          0         0      0       0  never      Idle (Admin)    ARISTA13T0
10.10.192.59    4  64014          0          0         0      0       0  never      Idle (Admin)    ARISTA14T0
10.10.192.61    4  64015          0          0         0      0       0  never      Idle (Admin)    ARISTA15T0
10.10.192.63    4  64016          0          0         0      0       0  never      Idle (Admin)    ARISTA16T0
10.10.192.65    4  64017          0          0         0      0       0  never      Idle (Admin)    ARISTA17T0
10.10.192.67    4  64018          0          0         0      0       0  never      Idle (Admin)    ARISTA18T0
10.10.192.69    4  64019          0          0         0      0       0  never      Idle (Admin)    ARISTA19T0
10.10.192.71    4  64020          0          0         0      0       0  never      Idle (Admin)    ARISTA20T0
10.106.0.1      4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA01T2
10.106.0.5      4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA03T2
10.106.0.9      4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA05T2
10.106.0.13     4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA07T2

Total number of neighbors 24

admin@:~$ show ip bgp summary -d all

IPv4 Unicast Summary:
asic0: BGP router identifier 10.0.107.16, local AS number 65100 vrf-id 0
BGP table version 21
asic1: BGP router identifier 10.0.107.17, local AS number 65100 vrf-id 0
BGP table version 24
asic2: BGP router identifier 10.0.107.18, local AS number 65100 vrf-id 0
BGP table version 21
asic3: BGP router identifier 10.0.107.19, local AS number 65100 vrf-id 0
BGP table version 24
RIB entries 170, using 31280 bytes of memory
Peers 40, using 836800 KiB of memory
Peer groups 20, using 1280 bytes of memory


Neighbhor       V     AS    MsgRcvd    MsgSent    TblVer    InQ    OutQ  Up/Down    State/PfxRcd    NeighborName
------------  ---  -----  ---------  ---------  --------  -----  ------  ---------  --------------  --------------
10.0.107.1      4  65100         16         22         0      0       0  00:09:02   4               ASIC0
10.0.107.3      4  65100         16         22         0      0       0  00:09:18   4               ASIC0
10.0.107.5      4  65100         16         18         0      0       0  00:09:00   4               ASIC1
10.0.107.7      4  65100         16         22         0      0       0  00:09:17   4               ASIC1
10.0.107.9      4  65100         21         23         0      0       0  00:10:59   4               ASIC2
10.0.107.11     4  65100         16         20         0      0       0  00:09:03   4               ASIC2
10.0.107.13     4  65100         16         22         0      0       0  00:09:02   4               ASIC3
10.0.107.15     4  65100         16         20         0      0       0  00:09:04   4               ASIC3
10.10.192.33    4  64001          0          0         0      0       0  never      Idle (Admin)    ARISTA01T0
10.10.192.35    4  64002          0          0         0      0       0  never      Idle (Admin)    ARISTA02T0
10.10.192.37    4  64003          0          0         0      0       0  never      Idle (Admin)    ARISTA03T0
10.10.192.39    4  64004          0          0         0      0       0  never      Idle (Admin)    ARISTA04T0
10.10.192.41    4  64005          0          0         0      0       0  never      Idle (Admin)    ARISTA05T0
10.10.192.43    4  64006          0          0         0      0       0  never      Idle (Admin)    ARISTA06T0
10.10.192.45    4  64007          0          0         0      0       0  never      Idle (Admin)    ARISTA07T0
10.10.192.47    4  64008          0          0         0      0       0  never      Idle (Admin)    ARISTA08T0
10.10.192.49    4  64009          0          0         0      0       0  never      Idle (Admin)    ARISTA09T0
10.10.192.51    4  64010          0          0         0      0       0  never      Idle (Admin)    ARISTA10T0
10.10.192.53    4  64011          0          0         0      0       0  never      Idle (Admin)    ARISTA11T0
10.10.192.55    4  64012          0          0         0      0       0  never      Idle (Admin)    ARISTA12T0
10.10.192.57    4  64013          0          0         0      0       0  never      Idle (Admin)    ARISTA13T0
10.10.192.59    4  64014          0          0         0      0       0  never      Idle (Admin)    ARISTA14T0
10.10.192.61    4  64015          0          0         0      0       0  never      Idle (Admin)    ARISTA15T0
10.10.192.63    4  64016          0          0         0      0       0  never      Idle (Admin)    ARISTA16T0
10.10.192.65    4  64017          0          0         0      0       0  never      Idle (Admin)    ARISTA17T0
10.10.192.67    4  64018          0          0         0      0       0  never      Idle (Admin)    ARISTA18T0
10.10.192.69    4  64019          0          0         0      0       0  never      Idle (Admin)    ARISTA19T0
10.10.192.71    4  64020          0          0         0      0       0  never      Idle (Admin)    ARISTA20T0
10.106.0.1      4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA01T2
10.106.0.5      4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA03T2
10.106.0.9      4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA05T2
10.106.0.13     4  65200          0          0         0      0       0  never      Idle (Admin)    ARISTA07T2

admin@:/$ sudo ip netns exec asic* show ip interfaces

Interface        Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
---------------  --------  -------------------  ------------  --------------  -------------
Loopback0                  172.16.132.64/32     up/up         N/A             N/A
Loopback4096               10.0.107.21/32       up/up         N/A             N/A
PortChannel4013            10.0.107.2/31        up/up         ASIC0           10.0.107.3
PortChannel4014            10.0.107.6/31        up/up         ASIC1           10.0.107.7
PortChannel4015            10.0.107.10/31       up/up         ASIC2           10.0.107.11
PortChannel4016            10.0.107.14/31       up/up         ASIC3           10.0.107.15
eth0                       240.127.1.7/24       up/up         N/A             N/A
lo                         127.0.0.1/8          up/up         N/A             N/A

admin@:/$ sudo ip netns exec asic* show ip interfaces

Interface        Master    IPv4 address/mask    Admin/Oper    BGP Neighbor    Neighbor IP
---------------  --------  -------------------  ------------  --------------  -------------
Loopback0                  172.16.132.64/32     up/up         N/A             N/A
Loopback4096               10.0.107.19/32       up/up         N/A             N/A
PortChannel1015            10.10.192.52/31      up/down       ARISTA11T0      10.10.192.53
PortChannel1016            10.10.192.54/31      up/down       ARISTA12T0      10.10.192.55
PortChannel1017            10.10.192.56/31      up/down       ARISTA13T0      10.10.192.57
PortChannel1018            10.10.192.58/31      up/down       ARISTA14T0      10.10.192.59
PortChannel1019            10.10.192.60/31      up/down       ARISTA15T0      10.10.192.61
PortChannel1020            10.10.192.62/31      up/down       ARISTA16T0      10.10.192.63
PortChannel1021            10.10.192.64/31      up/down       ARISTA17T0      10.10.192.65
PortChannel1022            10.10.192.66/31      up/down       ARISTA18T0      10.10.192.67
PortChannel1023            10.10.192.68/31      up/down       ARISTA19T0      10.10.192.69
PortChannel1024            10.10.192.70/31      up/down       ARISTA20T0      10.10.192.71
PortChannel4007            10.0.107.13/31       up/up         ASIC4           10.0.107.12
PortChannel4008            10.0.107.15/31       up/up         ASIC5           10.0.107.14
eth0                       240.127.1.2/24       up/up         N/A             N/A
lo                         127.0.0.1/8          up/up         N/A             N/A

```

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
@judyjoseph Should we remove the internal sessions from show commands too? I feel it as an implementation details.
If we need to investigate issues with it, we could use vtysh

**Comment by judyjoseph** [comment]
> @judyjoseph Should we remove the internal sessions from `show` commands too? I feel it as an implementation details.
> If we need to investigate bgp issues with the local sessions in the future , we could use `vtysh`

Yes Pavel, we don't display the internal bgp sessions by default, I have added the o/p of "show ip bgp summary" in the PR description. It will be shown only if user gives the option "-d all" explicitly as the command below. 
"show ip bgp summary -d all"

**Review by pavel-shirshov — DISMISSED** [review]

**Comment by judyjoseph** [comment]
@pavel-shirshov @arlakshm, please take a look. I wanted to update the unit tests as well..

**Review by pavel-shirshov — APPROVED** [review]

**Comment by rlhui** [comment]
@judyjoseph  - is this one still needed to be cherry-picked to 201911?

@arlakshm  - please review/approve? Thanks.

**Comment by abdosi** [comment]
@rlhui already in 20199 via direct pr for 201911

**Pull request merged**
