### PR TITLE
[decode-syseeprom] fix getattribute check for some platforms

### PR DESCRIPTION
**Pull request by mykolaf**
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

Fixes: #828 
**- What I did**
For some platforms which implement the eeprom plugin by inheriting from TlvInfoDecoder, the line
`t.getattr('read_eeprom_db', None) == None:`
results in an error:
`AttributeError: 'board' object has no attribute 'getattr'`

The cause for that is that TlvInfoDecoder inherits from `object`, and looks like for object and derived classes there is no `__getattr__`.
**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**
```
sudo decode-syseeprom
Traceback (most recent call last):
  File "/usr/bin/decode-syseeprom", line 175, in <module>
    exit(main())
  File "/usr/bin/decode-syseeprom", line 58, in main
    or t.getattr('read_eeprom_db', None) == None:
AttributeError: 'board' object has no attribute 'getattr'
```
**- New command output (if the output of a command-line utility has changed)**
```
sudo decode-syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 573
TLV Name             Code Len Value
-------------------- ---- --- -----
```

### CODE REVIEW

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by mykolaf** [comment]
The issue was introduced by [commit](https://github.com/Azure/sonic-utilities/commit/1fc2c3d880e65f71401ba59c495c1477b1628457) 
ATM it's not included in 201911 branch, so there is no need to Include this fix in  201911 branch)

**Comment by mykolaf** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by akokhan** [comment]
retest this please

**Comment by abdosi** [comment]
@mykolaf Please Create PR for 201911 as cherry-pick is not clean

**Comment by abdosi** [comment]
@mykolaf  Remainder again.
@liat-grozovik

**Pull request merged**
