### PR TITLE
Add an on/off knob for BGP EOIU pulling on warm restart

### PR DESCRIPTION
**Pull request by heidinet2007**
Add a knob to turn on/off the BGP EOIU pulling when BGP warm restart.  By default, it's off. 
This is to address review comments for https://github.com/Azure/sonic-buildimage/pull/2823

Other related PR

https://github.com/Azure/sonic-buildimage/pull/3489

https://github.com/Azure/sonic-buildimage/pull/2823
https://github.com/Azure/sonic-swss-common/pull/273
https://github.com/Azure/sonic-swss/pull/856

<pre>
root@ASW-7001:~# config warm_restart bgp_eoiu true
root@ASW-7001:~# show warm_restart config 
name    enable    timer_name    timer_duration    eoiu_enable
------  --------  ------------  ----------------  -------------
bgp     false     NULL          NULL              true

root@ASW-7001:~# config warm_restart bgp_eoiu false
root@ASW-7001:~# show warm_restart config 
name    enable    timer_name    timer_duration    eoiu_enable
------  --------  ------------  ----------------  -------------
bgp     false     NULL           NULL             false

root@ASW-7001:~# config warm_restart bgp_timer 120
root@ASW-7001:~# show warm_restart config 
name    enable    timer_name      timer_duration  eoiu_enable
------  --------  ------------  ----------------  -------------
bgp     false     bgp_timer     120               false

root@ASW-7001:~# config warm_restart bgp_eoiu true
root@ASW-7001:~# show warm_restart config 
name    enable    timer_name      timer_duration  eoiu_enable
------  --------  ------------  ----------------  -------------
bgp      false    bgp_timer     120               true

</pre>

### CODE REVIEW

**Comment by pavel-shirshov** [comment]
retest default please

**Comment by pavel-shirshov** [comment]
I'm ok if Joe approved it. I'm not an expert in this library

**Comment by pavel-shirshov** [comment]
retest this please

**Comment by yxieca** [comment]
retest this please

**Pull request merged**
