### PR TITLE
[sflow] Add mVRF support

### PR DESCRIPTION
**Pull request by GarrickHe**
* Add mVRF support and options to CLICK CLI

Signed-off-by: Garrick He <garrick_he@dell.com>

**- What I did**
Add options to allow mVRF configuration for sFlow collectors

**- How I did it**
Update the show/main.py and confg/main.py scripts

**- How to verify it**
Check output of CLICK CLI:

```
admin@sonic:~$ sudo config sflow collector add col1 1.1.1.1 --port 1111 --vrf mgmt
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          down
  sFlow Polling Interval:     default
  sFlow AgentID:              default

  1 Collectors configured:
    Name: col1                IP addr: 1.1.1.1         UDP port: 1111   VRF: mgmt
admin@sonic:~$ sudo config sflow collector add col2 1.1.1.2
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          down
  sFlow Polling Interval:     default
  sFlow AgentID:              default

  2 Collectors configured:
    Name: col1                IP addr: 1.1.1.1         UDP port: 1111   VRF: mgmt
    Name: col2                IP addr: 1.1.1.2         UDP port: 6343   VRF: default
admin@sonic:~$ sudo config sflow collector add col1 1.1.1.1 --port 1111 --vrf wrong
Invalid VRF (only default or mgmt)
admin@sonic:~$
```

**- Previous command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ sudo config sflow collector add col1 1.1.1.1 --port 1111
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          down
  sFlow Polling Interval:     default
  sFlow AgentID:              default

  1 Collectors configured:
    Name: col1                IP addr: 1.1.1.1         UDP port: 1111
admin@sonic:~$ sudo config sflow collector add col2 1.1.1.2
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          down
  sFlow Polling Interval:     default
  sFlow AgentID:              default

  2 Collectors configured:
    Name: col1                IP addr: 1.1.1.1         UDP port: 1111
    Name: col2                IP addr: 1.1.1.2         UDP port: 6343
```

**- New command output (if the output of a command-line utility has changed)**
```
admin@sonic:~$ sudo config sflow collector add col1 1.1.1.1 --port 1111 --vrf mgmt
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          down
  sFlow Polling Interval:     default
  sFlow AgentID:              default

  1 Collectors configured:
    Name: col1                IP addr: 1.1.1.1         UDP port: 1111   VRF: mgmt
admin@sonic:~$ sudo config sflow collector add col2 1.1.1.2
admin@sonic:~$ show sflow

sFlow Global Information:
  sFlow Admin State:          down
  sFlow Polling Interval:     default
  sFlow AgentID:              default

  2 Collectors configured:
    Name: col1                IP addr: 1.1.1.1         UDP port: 1111   VRF: mgmt
    Name: col2                IP addr: 1.1.1.2         UDP port: 6343   VRF: default
admin@sonic:~$ sudo config sflow collector add col1 1.1.1.1 --port 1111 --vrf wrong
Invalid VRF (only default or mgmt)
admin@sonic:~$
```

### CODE REVIEW

**Comment by GarrickHe** [comment]
**DO NOT MERGE UNTIL THIS PR IS MERGED:**

https://github.com/Azure/sonic-buildimage/pull/5904

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
retest this please

**Comment by prsunny** [comment]
@GarrickHe , please fix the test failures on sflow

**Comment by GarrickHe** [comment]
@prsunny - I looked in the details of the 'default' test. I don't see any information on what failed. Can you please tell me what am I suppose to fix? Thank you.

**Comment by prsunny** [comment]
https://sonic-jenkins.westus2.cloudapp.azure.com/job/common/job/sonic-utilities-build-pr/2896/consoleFull

```
10:07:10      def test_show_sflow(self):
10:07:10          runner = CliRunner()
10:07:10          result = runner.invoke(show.cli.commands["sflow"], [], obj=Db())
10:07:10          print(result.exit_code, result.output)
10:07:10  >       assert result.exit_code == 0
10:07:10  E       AssertionError: assert 1 == 0
10:07:10  E        +  where 1 = <Result KeyError('collector_vrf',)>.exit_code
```

**Comment by GarrickHe** [comment]
retest this please

**Comment by GarrickHe** [comment]
retest this please

**Review by prsunny — APPROVED** [review]

**Comment by harveylu-ruijie** [comment]
@GarrickHe @prsunny hi guys. I would wanna know why set this limitiion in is_valid_collector_info()
Snipaste_2024-09-27_11-16-39
Why the vrf here can not be another name , like 'Vrf1'， 'Vrf2' ?
Thanks!

**Pull request merged**
