### PR TITLE
[show] Break some groups out into their own modules

### PR DESCRIPTION
**Pull request by jleveque**
In order to organize code better, reduce the size of large files and help granularize unit test coverage reports, break out the following groups from show/main.py into their own files:

- acl
- dropcounters
- gearbox
- kdump
- nat
- platform
- processes
- sflow
- vnet
- vxlan
- warm_restart

Also remove the following check from utilities_common/cli.py:run_command() and fix all tests which relied upon it:

```
if os.getenv("UTILITIES_UNIT_TESTING") == "1":
        return
```

### CODE REVIEW

**Comment by jleveque** [comment]
Retest this please

**Comment by lguohan** [comment]
this is good change, but how do you verify no regression?

**Comment by jleveque** [comment]
> this is good change, but how do you verify no regression?

I've tested that the commands continue to execute. However, to ensure no functionality has regressed, I'm relying on unit tests, albeit there is not 100% coverage.

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
LGTM alert is not related to this PR; it is pre-existing.

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Comment by jleveque** [comment]
Retest this please

**Review by lguohan — APPROVED** [review]

**Pull request merged**
