### PR TITLE
check for unsupported speeds corrected

### PR DESCRIPTION
**Pull request by MaratGubaiev**
https://github.com/Azure/sonic-buildimage/issues/9327 fixed

#### What I did
I changed string search to list search.

#### How to verify it
Perform ```sudo config interface speed Ethernet0 500```
You will see the error message.
Perform ```show interfaces status```
Ethernet0 speed will remain unchanged.

### CODE REVIEW

**Comment by MaratGubaiev** [comment]
@prsunny @zhangyanzhao
Can anybody please assign reviewers?

**Comment by liat-grozovik** [comment]
@MaratGubaiev can you please fix conflict and add unit test to cover the check as well?

**Comment by MaratGubaiev** [comment]
> @MaratGubaiev can you please fix conflict and add unit test to cover the check as well?

It is already fixed here: https://github.com/Azure/sonic-utilities/pull/1952

**Pull request closed without merging**
