### PR TITLE
 Support display speed less than 1G on 'show interfaces status' or 'i…

### PR DESCRIPTION
**Pull request by PrabhuSreenivasan**
…ntfutil status output'

**- What I did**
Fixed “show interfaces status” command output to show speeds less than 1G properly. 

**- How I did it**
Modified the intfutil script to display speeds less than 1G. Speeds less than 1G were displayed as “G”. Now if the speed is less than 1G, say 100Mbps, it shows  “100M”.

**- How to verify it**
portconfig -p Ethernet0 -s 100
show interface status

**- Previous command output (if the output of a command-line utility has changed)**

```
root@sonic:/home/admin# show interface status | head
  Interface    Lanes    Speed    MTU      Alias    Oper    Admin    Type
-----------  -------  -------  -----  ---------  ------  -------  ------
  Ethernet0       13        G   9100   tenGigE0    down       up     SFP
  Ethernet1       14      N/A   9100   tenGigE1    down       up     N/A
  Ethernet2       15      N/A   9100   tenGigE2    down       up     SFP
  Ethernet3       16      N/A   9100   tenGigE3    down       up     N/A
  Ethernet4       21      N/A   9100   tenGigE4    down       up     SFP
  Ethernet5       22      N/A   9100   tenGigE5    down       up     N/A
  Ethernet6       23      N/A   9100   tenGigE6    down       up     N/A
  Ethernet7       24      N/A   9100   tenGigE7    down       up     N/A
```

**- New command output (if the output of a command-line utility has changed)**

```
root@sonic:/home/admin# show interface status | head
  Interface    Lanes    Speed    MTU      Alias    Oper    Admin    Type
-----------  -------  -------  -----  ---------  ------  -------  ------
  Ethernet0       13     100M   9100   tenGigE0    down       up     SFP
  Ethernet1       14      N/A   9100   tenGigE1    down       up     N/A
  Ethernet2       15      N/A   9100   tenGigE2    down       up     SFP
  Ethernet3       16      N/A   9100   tenGigE3    down       up     N/A
  Ethernet4       21      N/A   9100   tenGigE4    down       up     SFP
  Ethernet5       22      N/A   9100   tenGigE5    down       up     N/A
  Ethernet6       23      N/A   9100   tenGigE6    down       up     N/A
  Ethernet7       24      N/A   9100   tenGigE7    down       up     N/A
```

-->

### CODE REVIEW

**Comment by lguohan** [comment]
retest this please

**Comment by PrabhuSreenivasan** [comment]
Tested and found working..

**Comment by PrabhuSreenivasan** [comment]
please pick this change for 201811 branch as well.

**Comment by jleveque** [comment]
Retest this please

**Pull request closed without merging**
