### PR TITLE
fdbshow and nbrshow use SonicV2Connector with decode_responses=True, and remove all the decode()

### PR DESCRIPTION
**Pull request by qiluo-msft**
**- What I did**
Following the plan in https://github.com/Azure/sonic-py-swsssdk/pull/89
1. fdbshow and nbrshow use SonicV2Connector with `decode_responses=True`
2. remove all the `decode()`

**- How I did it**

**- How to verify it**

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

### CODE REVIEW

**Review by tahmed-dev — APPROVED** [review]

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
Retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by qiluo-msft** [comment]
retest this please

**Comment by qiluo-msft** [comment]
retest this please

**Pull request merged**
