### PR TITLE
[techsupport] Removed -t option and other missing fixes for techsupport error reporting

### PR DESCRIPTION
**Pull request by vivekreddynv**
Signed-off-by: Vivek Reddy Karri <vkarri@nvidia.com>

#### What I did

This PR include some fixes which were missed for #1723 

i.e. removing -t option from the docker exec commands. to understand why the -it option was removed, refer #1723.

Also, the show techsupport exits with $RETURN_CODE only when --redirect-stderr option is used.

### CODE REVIEW

**Comment by dgsudharsan** [comment]
@yxieca  @qiluo-msft  Can you please help merging this?

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by vivekreddynv** [comment]
It's already ported to 202012, (https://github.com/Azure/sonic-utilities/pull/1833, https://github.com/Azure/sonic-utilities/pull/1854) & 202106 (https://github.com/Azure/sonic-utilities/pull/1843)

**Pull request merged**
