### PR TITLE
Show sflow interface to display all interfaces enabled for sflow

### PR DESCRIPTION
**Pull request by tonytitus**
**- What I did**
"show sflow interface" is updated to show all interfaces enabled for sflow

**- How I did it**
Updated sflow show command

**- How to verify it**
Run "show sflow interface" and confirm all interfaces are displayed

**- Previous command output (if the output of a command-line utility has changed)**

# show sflow interface

sFlow interface configurations
+-------------+---------------+-----------------+
| Interface   | Admin State   |   Sampling Rate |
+=============+===============+=================+
| Ethernet4   | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet12  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet16  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet26  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet34  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet42  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet52  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet58  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet68  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet78  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet84  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet88  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet98  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet110 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet112 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet120 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet132 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet142 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet150 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet158 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet164 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet174 | up            |           10000 |
+-------------+---------------+-----------------+

**- New command output (if the output of a command-line utility has changed)**

# show sflow interface

sFlow interface configurations
+-------------+---------------+-----------------+
| Interface   | Admin State   |   Sampling Rate |
+=============+===============+=================+
| Ethernet0   | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet2   | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet4   | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet6   | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet8   | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet10  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet12  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet14  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet16  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet18  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet20  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet22  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet24  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet26  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet28  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet30  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet32  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet34  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet36  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet38  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet40  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet42  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet44  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet46  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet48  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet50  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet52  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet54  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet56  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet58  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet60  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet62  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet64  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet66  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet68  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet70  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet72  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet74  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet76  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet78  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet80  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet82  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet84  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet86  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet88  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet90  | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet92  | up            |           10000 |
+-------------+---------------+-----------------+
...
...
+-------------+---------------+-----------------+
| Ethernet224 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet226 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet228 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet230 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet232 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet234 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet236 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet238 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet240 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet242 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet244 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet246 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet248 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet250 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet252 | up            |           10000 |
+-------------+---------------+-----------------+
| Ethernet254 | up            |           10000 |
+-------------+---------------+-----------------+

### CODE REVIEW

**Comment by GarrickHe** [comment]
@tonytitus - Can you show the output when you run `show sflow interface` pre/post change? Thank you.

**Comment by tonytitus** [comment]
> @tonytitus - Can you show the output when you run `show sflow interface` pre/post change? Thank you.

Added

**Review by GarrickHe — APPROVED** [review]
LGTM

**Comment by prsunny** [comment]
Can you raise this PR to master?

**Comment by tonytitus** [comment]
> Can you raise this PR to master?

Raised  https://github.com/Azure/sonic-utilities/pull/1143 for master

Any idea why build is failing?

**Comment by tonytitus** [comment]
retest default

**Comment by prsunny** [comment]
@tonytitus , merged the [PR ](https://github.com/Azure/sonic-utilities/pull/1143)to master and marked for pick to 201911. You can close this PR

**Pull request closed without merging**
