### PR TITLE
[test] Update unit test coverage for command 'show mac'

### PR DESCRIPTION
**Pull request by maksymbelei95**
* Adding unit tests for CLI command 'show mac'. Testing
  both CLI command and 'fdbshow' script.

Signed-off-by: Maksym Belei <Maksym_Belei@jabil.com>

#### What I did
Unit test coverage has updated for CLI command `show mac`. The PR includes test case for https://github.com/Azure/sonic-utilities/pull/1368.

#### How I did it
Added new unit tests for command `show mac`. Tested both CLI command and `fdbshow` script directly.

#### How to verify it
See unit test coverage report.

### CODE REVIEW

**Comment by maksymbelei95** [comment]
@gechiang, I have added unit tests for 'show mac', including test case for https://github.com/Azure/sonic-utilities/pull/1368, as you asked before. Could you check the PR?

**Comment by gechiang** [comment]
@maksymbelei95 testcases looks good.  According to the test report it shows following:
scripts/fdbshow                                 109     11     48     10    87%
Can you add a few more tests to boost the code coverage to above 90%?
Thank you!

**Comment by maksymbelei95** [comment]
@gechiang, I have updated unit tests and made some refactoring in fdshow script. Could you check the updates? Currently, fdbshow has covered by 100%.

**Review by gechiang — APPROVED** [review]

**Comment by gechiang** [comment]
Nice work!
Thanks for providing all variation of test cases to provide the code coverage!

**Pull request merged**
