### PR TITLE
Use swsscommon module instead of swsssdk ( swsssdk is deprecated)

### PR DESCRIPTION
**Pull request by ayurkiv-nvda**
#### What I did
Changed code to use use swsscommon instead of swsssdk in counterpoll

#### How I did it
Removed an explicit function call from sdsssdk module

#### How to verify it
run counterpoll tests

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@ayurkiv-nvda  not sure i understand the motivation. Is it deprecated code? is it a bug fix?
to which branch it should go?

**Review by qiluo-msft — APPROVED** [review]

**Comment by liat-grozovik** [comment]
retest this please

**Comment by liat-grozovik** [comment]
retest this please

**Comment by qiluo-msft** [comment]
No need to retest "default", it is not required any more so Jenkins job is disabled.

**Review by jleveque — APPROVED** [review]

**Pull request merged**
