### PR TITLE
Validations checks while creating and deleting a Portchannel

### PR DESCRIPTION
**Pull request by AkhileshSamineni**
Added below validation checks when a portchannel is created by the user:
    1 if a given portchannel name is valid or not
    2 if a given portchannel name is already created by user (exists in CONFIG_DB)

Added below validation checks when a portchannel is attempted for deletion by the user:
    1 if a given portchannel name is valid or not
    2 if a given portchannel name exists in exists in CONFIG_DB or not (throw an error if it does not exist)

More details : 
Issue 1 : Creating a invalid Portchannel name

If we create a portchannel with invalid name, it gets added to CONFIG_DB, like below
root@sonic:/home/admin# config portchannel add PortChan001
root@sonic:/home/admin#
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChan001
root@sonic:/home/admin#

Fix: Added a PortChannel name validation check, like below

root@sonic:/home/admin# config portchannel add PortChan001
Usage: config portchannel add [OPTIONS] <portchannel_name>

Error: PortChan001 is invalid!, name should have prefix 'PortChannel' and suffix '<0-9999>'
root@sonic:/home/admin#

Issue 2 : Creating a same PortChannel again and deleting the portchannel which is not exists

If we create a same portchannel again, it is allowing, like below
root@sonic:/home/admin# config portchannel add PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# config portchannel add PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChannel0001
root@sonic:/home/admin#

If we delete a portchannel which is not exists, it is allowing
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# config portchannel del PortChannel0002
root@sonic:/home/admin#

Fix : Added a validation check like given portchannel exists in CONFIG_DB or not

While creating a portchannel
root@sonic:/home/admin# config portchannel add PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# config portchannel add PortChannel0001
Usage: config portchannel add [OPTIONS] <portchannel_name>

Error: PortChannel0001 already exists!
root@sonic:/home/admin#

While deleting a portchannel
root@sonic:/home/admin# sonic-db-cli CONFIG_DB keys \*PORTCHANNEL\*
PORTCHANNEL|PortChannel0001
root@sonic:/home/admin#
root@sonic:/home/admin# config portchannel del PortChannel0002
Usage: config portchannel del [OPTIONS] <portchannel_name>

Error: PortChannel0002 is not present.
root@sonic:/home/admin#

Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>

### CODE REVIEW

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
Retest this please.

**Comment by AkhileshSamineni** [comment]
@lguohan Please review the changes.

**Comment by prsunny** [comment]
Does https://github.com/Azure/sonic-utilities/pull/1328 supersedes this PR?

**Comment by AkhileshSamineni** [comment]
> Does #1328 supersedes this PR?

@prsunny  Yes, I have resolved the merge conflicts. Please review the changes now.

**Comment by AkhileshSamineni** [comment]
@prsunny @lguohan Please review and merge the PR.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
