### PR TITLE
[show][platform summary] Add chassis type in the platform summary

### PR DESCRIPTION
**Pull request by smaheshm**
#### What I did
Add chassis type in the platform summary on chassis platforms.

#### How I did it
Get the switch type from platform_info() API.

#### How to verify it
```
admin@str2-chasssis-lc3-1:~$ show platform summary
Platform: chassis_lc
HwSKU: chassis
ASIC: broadcom
ASIC Count: 1
Serial Number: xyz
Model Number: chassis-LC
Hardware Revision: N/A
Switch Type: voq

```

### CODE REVIEW

**Comment by smaheshm** [comment]
commit after https://github.com/Azure/sonic-buildimage/pull/9227

**Review by judyjoseph — APPROVED** [review]

**Pull request merged**
